// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

/**
 * <pre>
 * --8&lt;-- [start:AgentSkill]
 * AgentSkill represents a unit of action/solution that the agent can perform.
 * One can think of this as a type of highly reliable solution that an agent
 * can be tasked to provide. Agents have the autonomy to choose how and when
 * to use specific skills, but clients should have confidence that if the
 * skill is defined that unit of action can be reliably performed.
 * </pre>
 *
 * Protobuf type {@code a2a.v1.AgentSkill}
 */
@com.google.protobuf.Generated
public final class AgentSkill extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.AgentSkill)
    AgentSkillOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "AgentSkill");
  }
  // Use AgentSkill.newBuilder() to construct.
  private AgentSkill(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AgentSkill() {
    id_ = "";
    name_ = "";
    description_ = "";
    tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    examples_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    inputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    outputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    security_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_AgentSkill_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_AgentSkill_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.a2a.v1.AgentSkill.class, com.google.a2a.v1.AgentSkill.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * Unique identifier of the skill within this agent.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique identifier of the skill within this agent.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * A human readable name for the skill.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A human readable name for the skill.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * A human (or llm) readable description of the skill
   * details and behaviors.
   * </pre>
   *
   * <code>string description = 3 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A human (or llm) readable description of the skill
   * details and behaviors.
   * </pre>
   *
   * <code>string description = 3 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * A set of tags for the skill to enhance categorization/utilization.
   * Example: ["cooking", "customer support", "billing"]
   * </pre>
   *
   * <code>repeated string tags = 4 [json_name = "tags"];</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   * A set of tags for the skill to enhance categorization/utilization.
   * Example: ["cooking", "customer support", "billing"]
   * </pre>
   *
   * <code>repeated string tags = 4 [json_name = "tags"];</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   * A set of tags for the skill to enhance categorization/utilization.
   * Example: ["cooking", "customer support", "billing"]
   * </pre>
   *
   * <code>repeated string tags = 4 [json_name = "tags"];</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   * A set of tags for the skill to enhance categorization/utilization.
   * Example: ["cooking", "customer support", "billing"]
   * </pre>
   *
   * <code>repeated string tags = 4 [json_name = "tags"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int EXAMPLES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList examples_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * A set of example queries that this skill is designed to address.
   * These examples should help the caller to understand how to craft requests
   * to the agent to achieve specific goals.
   * Example: ["I need a recipe for bread"]
   * </pre>
   *
   * <code>repeated string examples = 5 [json_name = "examples"];</code>
   * @return A list containing the examples.
   */
  public com.google.protobuf.ProtocolStringList
      getExamplesList() {
    return examples_;
  }
  /**
   * <pre>
   * A set of example queries that this skill is designed to address.
   * These examples should help the caller to understand how to craft requests
   * to the agent to achieve specific goals.
   * Example: ["I need a recipe for bread"]
   * </pre>
   *
   * <code>repeated string examples = 5 [json_name = "examples"];</code>
   * @return The count of examples.
   */
  public int getExamplesCount() {
    return examples_.size();
  }
  /**
   * <pre>
   * A set of example queries that this skill is designed to address.
   * These examples should help the caller to understand how to craft requests
   * to the agent to achieve specific goals.
   * Example: ["I need a recipe for bread"]
   * </pre>
   *
   * <code>repeated string examples = 5 [json_name = "examples"];</code>
   * @param index The index of the element to return.
   * @return The examples at the given index.
   */
  public java.lang.String getExamples(int index) {
    return examples_.get(index);
  }
  /**
   * <pre>
   * A set of example queries that this skill is designed to address.
   * These examples should help the caller to understand how to craft requests
   * to the agent to achieve specific goals.
   * Example: ["I need a recipe for bread"]
   * </pre>
   *
   * <code>repeated string examples = 5 [json_name = "examples"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the examples at the given index.
   */
  public com.google.protobuf.ByteString
      getExamplesBytes(int index) {
    return examples_.getByteString(index);
  }

  public static final int INPUT_MODES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList inputModes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Possible input modalities supported.
   * </pre>
   *
   * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
   * @return A list containing the inputModes.
   */
  public com.google.protobuf.ProtocolStringList
      getInputModesList() {
    return inputModes_;
  }
  /**
   * <pre>
   * Possible input modalities supported.
   * </pre>
   *
   * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
   * @return The count of inputModes.
   */
  public int getInputModesCount() {
    return inputModes_.size();
  }
  /**
   * <pre>
   * Possible input modalities supported.
   * </pre>
   *
   * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
   * @param index The index of the element to return.
   * @return The inputModes at the given index.
   */
  public java.lang.String getInputModes(int index) {
    return inputModes_.get(index);
  }
  /**
   * <pre>
   * Possible input modalities supported.
   * </pre>
   *
   * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the inputModes at the given index.
   */
  public com.google.protobuf.ByteString
      getInputModesBytes(int index) {
    return inputModes_.getByteString(index);
  }

  public static final int OUTPUT_MODES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList outputModes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Possible output modalities produced
   * </pre>
   *
   * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
   * @return A list containing the outputModes.
   */
  public com.google.protobuf.ProtocolStringList
      getOutputModesList() {
    return outputModes_;
  }
  /**
   * <pre>
   * Possible output modalities produced
   * </pre>
   *
   * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
   * @return The count of outputModes.
   */
  public int getOutputModesCount() {
    return outputModes_.size();
  }
  /**
   * <pre>
   * Possible output modalities produced
   * </pre>
   *
   * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
   * @param index The index of the element to return.
   * @return The outputModes at the given index.
   */
  public java.lang.String getOutputModes(int index) {
    return outputModes_.get(index);
  }
  /**
   * <pre>
   * Possible output modalities produced
   * </pre>
   *
   * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the outputModes at the given index.
   */
  public com.google.protobuf.ByteString
      getOutputModesBytes(int index) {
    return outputModes_.getByteString(index);
  }

  public static final int SECURITY_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<com.google.a2a.v1.Security> security_;
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * Security schemes necessary for the agent to leverage this skill.
   * As in the overall AgentCard.security, this list represents a logical OR of
   * security requirement objects. Each object is a set of security schemes
   * that must be used together (a logical AND).
   * </pre>
   *
   * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.a2a.v1.Security> getSecurityList() {
    return security_;
  }
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * Security schemes necessary for the agent to leverage this skill.
   * As in the overall AgentCard.security, this list represents a logical OR of
   * security requirement objects. Each object is a set of security schemes
   * that must be used together (a logical AND).
   * </pre>
   *
   * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.a2a.v1.SecurityOrBuilder> 
      getSecurityOrBuilderList() {
    return security_;
  }
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * Security schemes necessary for the agent to leverage this skill.
   * As in the overall AgentCard.security, this list represents a logical OR of
   * security requirement objects. Each object is a set of security schemes
   * that must be used together (a logical AND).
   * </pre>
   *
   * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
   */
  @java.lang.Override
  public int getSecurityCount() {
    return security_.size();
  }
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * Security schemes necessary for the agent to leverage this skill.
   * As in the overall AgentCard.security, this list represents a logical OR of
   * security requirement objects. Each object is a set of security schemes
   * that must be used together (a logical AND).
   * </pre>
   *
   * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.Security getSecurity(int index) {
    return security_.get(index);
  }
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * Security schemes necessary for the agent to leverage this skill.
   * As in the overall AgentCard.security, this list represents a logical OR of
   * security requirement objects. Each object is a set of security schemes
   * that must be used together (a logical AND).
   * </pre>
   *
   * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.SecurityOrBuilder getSecurityOrBuilder(
      int index) {
    return security_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, tags_.getRaw(i));
    }
    for (int i = 0; i < examples_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, examples_.getRaw(i));
    }
    for (int i = 0; i < inputModes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, inputModes_.getRaw(i));
    }
    for (int i = 0; i < outputModes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, outputModes_.getRaw(i));
    }
    for (int i = 0; i < security_.size(); i++) {
      output.writeMessage(8, security_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < examples_.size(); i++) {
        dataSize += computeStringSizeNoTag(examples_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getExamplesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < inputModes_.size(); i++) {
        dataSize += computeStringSizeNoTag(inputModes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInputModesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < outputModes_.size(); i++) {
        dataSize += computeStringSizeNoTag(outputModes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOutputModesList().size();
    }
    for (int i = 0; i < security_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, security_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.a2a.v1.AgentSkill)) {
      return super.equals(obj);
    }
    com.google.a2a.v1.AgentSkill other = (com.google.a2a.v1.AgentSkill) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getExamplesList()
        .equals(other.getExamplesList())) return false;
    if (!getInputModesList()
        .equals(other.getInputModesList())) return false;
    if (!getOutputModesList()
        .equals(other.getOutputModesList())) return false;
    if (!getSecurityList()
        .equals(other.getSecurityList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    if (getExamplesCount() > 0) {
      hash = (37 * hash) + EXAMPLES_FIELD_NUMBER;
      hash = (53 * hash) + getExamplesList().hashCode();
    }
    if (getInputModesCount() > 0) {
      hash = (37 * hash) + INPUT_MODES_FIELD_NUMBER;
      hash = (53 * hash) + getInputModesList().hashCode();
    }
    if (getOutputModesCount() > 0) {
      hash = (37 * hash) + OUTPUT_MODES_FIELD_NUMBER;
      hash = (53 * hash) + getOutputModesList().hashCode();
    }
    if (getSecurityCount() > 0) {
      hash = (37 * hash) + SECURITY_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.a2a.v1.AgentSkill parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.a2a.v1.AgentSkill parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.a2a.v1.AgentSkill parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.AgentSkill parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.a2a.v1.AgentSkill prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:AgentSkill]
   * AgentSkill represents a unit of action/solution that the agent can perform.
   * One can think of this as a type of highly reliable solution that an agent
   * can be tasked to provide. Agents have the autonomy to choose how and when
   * to use specific skills, but clients should have confidence that if the
   * skill is defined that unit of action can be reliably performed.
   * </pre>
   *
   * Protobuf type {@code a2a.v1.AgentSkill}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.AgentSkill)
      com.google.a2a.v1.AgentSkillOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_AgentSkill_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_AgentSkill_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.a2a.v1.AgentSkill.class, com.google.a2a.v1.AgentSkill.Builder.class);
    }

    // Construct using com.google.a2a.v1.AgentSkill.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = "";
      description_ = "";
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      examples_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      inputModes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      outputModes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (securityBuilder_ == null) {
        security_ = java.util.Collections.emptyList();
      } else {
        security_ = null;
        securityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_AgentSkill_descriptor;
    }

    @java.lang.Override
    public com.google.a2a.v1.AgentSkill getDefaultInstanceForType() {
      return com.google.a2a.v1.AgentSkill.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.a2a.v1.AgentSkill build() {
      com.google.a2a.v1.AgentSkill result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.a2a.v1.AgentSkill buildPartial() {
      com.google.a2a.v1.AgentSkill result = new com.google.a2a.v1.AgentSkill(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.a2a.v1.AgentSkill result) {
      if (securityBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          security_ = java.util.Collections.unmodifiableList(security_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.security_ = security_;
      } else {
        result.security_ = securityBuilder_.build();
      }
    }

    private void buildPartial0(com.google.a2a.v1.AgentSkill result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        tags_.makeImmutable();
        result.tags_ = tags_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        examples_.makeImmutable();
        result.examples_ = examples_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        inputModes_.makeImmutable();
        result.inputModes_ = inputModes_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        outputModes_.makeImmutable();
        result.outputModes_ = outputModes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.a2a.v1.AgentSkill) {
        return mergeFrom((com.google.a2a.v1.AgentSkill)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.a2a.v1.AgentSkill other) {
      if (other == com.google.a2a.v1.AgentSkill.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ |= 0x00000008;
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (!other.examples_.isEmpty()) {
        if (examples_.isEmpty()) {
          examples_ = other.examples_;
          bitField0_ |= 0x00000010;
        } else {
          ensureExamplesIsMutable();
          examples_.addAll(other.examples_);
        }
        onChanged();
      }
      if (!other.inputModes_.isEmpty()) {
        if (inputModes_.isEmpty()) {
          inputModes_ = other.inputModes_;
          bitField0_ |= 0x00000020;
        } else {
          ensureInputModesIsMutable();
          inputModes_.addAll(other.inputModes_);
        }
        onChanged();
      }
      if (!other.outputModes_.isEmpty()) {
        if (outputModes_.isEmpty()) {
          outputModes_ = other.outputModes_;
          bitField0_ |= 0x00000040;
        } else {
          ensureOutputModesIsMutable();
          outputModes_.addAll(other.outputModes_);
        }
        onChanged();
      }
      if (securityBuilder_ == null) {
        if (!other.security_.isEmpty()) {
          if (security_.isEmpty()) {
            security_ = other.security_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureSecurityIsMutable();
            security_.addAll(other.security_);
          }
          onChanged();
        }
      } else {
        if (!other.security_.isEmpty()) {
          if (securityBuilder_.isEmpty()) {
            securityBuilder_.dispose();
            securityBuilder_ = null;
            security_ = other.security_;
            bitField0_ = (bitField0_ & ~0x00000080);
            securityBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSecurityFieldBuilder() : null;
          } else {
            securityBuilder_.addAllMessages(other.security_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagsIsMutable();
              tags_.add(s);
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureExamplesIsMutable();
              examples_.add(s);
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureInputModesIsMutable();
              inputModes_.add(s);
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureOutputModesIsMutable();
              outputModes_.add(s);
              break;
            } // case 58
            case 66: {
              com.google.a2a.v1.Security m =
                  input.readMessage(
                      com.google.a2a.v1.Security.parser(),
                      extensionRegistry);
              if (securityBuilder_ == null) {
                ensureSecurityIsMutable();
                security_.add(m);
              } else {
                securityBuilder_.addMessage(m);
              }
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Unique identifier of the skill within this agent.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier of the skill within this agent.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier of the skill within this agent.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier of the skill within this agent.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier of the skill within this agent.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * A human readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A human readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A human readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A human readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A human readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * A human (or llm) readable description of the skill
     * details and behaviors.
     * </pre>
     *
     * <code>string description = 3 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A human (or llm) readable description of the skill
     * details and behaviors.
     * </pre>
     *
     * <code>string description = 3 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A human (or llm) readable description of the skill
     * details and behaviors.
     * </pre>
     *
     * <code>string description = 3 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A human (or llm) readable description of the skill
     * details and behaviors.
     * </pre>
     *
     * <code>string description = 3 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A human (or llm) readable description of the skill
     * details and behaviors.
     * </pre>
     *
     * <code>string description = 3 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagsIsMutable() {
      if (!tags_.isModifiable()) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      tags_.makeImmutable();
      return tags_;
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of tags for the skill to enhance categorization/utilization.
     * Example: ["cooking", "customer support", "billing"]
     * </pre>
     *
     * <code>repeated string tags = 4 [json_name = "tags"];</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList examples_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureExamplesIsMutable() {
      if (!examples_.isModifiable()) {
        examples_ = new com.google.protobuf.LazyStringArrayList(examples_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @return A list containing the examples.
     */
    public com.google.protobuf.ProtocolStringList
        getExamplesList() {
      examples_.makeImmutable();
      return examples_;
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @return The count of examples.
     */
    public int getExamplesCount() {
      return examples_.size();
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @param index The index of the element to return.
     * @return The examples at the given index.
     */
    public java.lang.String getExamples(int index) {
      return examples_.get(index);
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the examples at the given index.
     */
    public com.google.protobuf.ByteString
        getExamplesBytes(int index) {
      return examples_.getByteString(index);
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @param index The index to set the value at.
     * @param value The examples to set.
     * @return This builder for chaining.
     */
    public Builder setExamples(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureExamplesIsMutable();
      examples_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @param value The examples to add.
     * @return This builder for chaining.
     */
    public Builder addExamples(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureExamplesIsMutable();
      examples_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @param values The examples to add.
     * @return This builder for chaining.
     */
    public Builder addAllExamples(
        java.lang.Iterable<java.lang.String> values) {
      ensureExamplesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, examples_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExamples() {
      examples_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of example queries that this skill is designed to address.
     * These examples should help the caller to understand how to craft requests
     * to the agent to achieve specific goals.
     * Example: ["I need a recipe for bread"]
     * </pre>
     *
     * <code>repeated string examples = 5 [json_name = "examples"];</code>
     * @param value The bytes of the examples to add.
     * @return This builder for chaining.
     */
    public Builder addExamplesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureExamplesIsMutable();
      examples_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList inputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureInputModesIsMutable() {
      if (!inputModes_.isModifiable()) {
        inputModes_ = new com.google.protobuf.LazyStringArrayList(inputModes_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @return A list containing the inputModes.
     */
    public com.google.protobuf.ProtocolStringList
        getInputModesList() {
      inputModes_.makeImmutable();
      return inputModes_;
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @return The count of inputModes.
     */
    public int getInputModesCount() {
      return inputModes_.size();
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @param index The index of the element to return.
     * @return The inputModes at the given index.
     */
    public java.lang.String getInputModes(int index) {
      return inputModes_.get(index);
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the inputModes at the given index.
     */
    public com.google.protobuf.ByteString
        getInputModesBytes(int index) {
      return inputModes_.getByteString(index);
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @param index The index to set the value at.
     * @param value The inputModes to set.
     * @return This builder for chaining.
     */
    public Builder setInputModes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureInputModesIsMutable();
      inputModes_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @param value The inputModes to add.
     * @return This builder for chaining.
     */
    public Builder addInputModes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureInputModesIsMutable();
      inputModes_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @param values The inputModes to add.
     * @return This builder for chaining.
     */
    public Builder addAllInputModes(
        java.lang.Iterable<java.lang.String> values) {
      ensureInputModesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, inputModes_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInputModes() {
      inputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Possible input modalities supported.
     * </pre>
     *
     * <code>repeated string input_modes = 6 [json_name = "inputModes"];</code>
     * @param value The bytes of the inputModes to add.
     * @return This builder for chaining.
     */
    public Builder addInputModesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureInputModesIsMutable();
      inputModes_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList outputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureOutputModesIsMutable() {
      if (!outputModes_.isModifiable()) {
        outputModes_ = new com.google.protobuf.LazyStringArrayList(outputModes_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @return A list containing the outputModes.
     */
    public com.google.protobuf.ProtocolStringList
        getOutputModesList() {
      outputModes_.makeImmutable();
      return outputModes_;
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @return The count of outputModes.
     */
    public int getOutputModesCount() {
      return outputModes_.size();
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @param index The index of the element to return.
     * @return The outputModes at the given index.
     */
    public java.lang.String getOutputModes(int index) {
      return outputModes_.get(index);
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the outputModes at the given index.
     */
    public com.google.protobuf.ByteString
        getOutputModesBytes(int index) {
      return outputModes_.getByteString(index);
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @param index The index to set the value at.
     * @param value The outputModes to set.
     * @return This builder for chaining.
     */
    public Builder setOutputModes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutputModesIsMutable();
      outputModes_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @param value The outputModes to add.
     * @return This builder for chaining.
     */
    public Builder addOutputModes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutputModesIsMutable();
      outputModes_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @param values The outputModes to add.
     * @return This builder for chaining.
     */
    public Builder addAllOutputModes(
        java.lang.Iterable<java.lang.String> values) {
      ensureOutputModesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, outputModes_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputModes() {
      outputModes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Possible output modalities produced
     * </pre>
     *
     * <code>repeated string output_modes = 7 [json_name = "outputModes"];</code>
     * @param value The bytes of the outputModes to add.
     * @return This builder for chaining.
     */
    public Builder addOutputModesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureOutputModesIsMutable();
      outputModes_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.util.List<com.google.a2a.v1.Security> security_ =
      java.util.Collections.emptyList();
    private void ensureSecurityIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        security_ = new java.util.ArrayList<com.google.a2a.v1.Security>(security_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.a2a.v1.Security, com.google.a2a.v1.Security.Builder, com.google.a2a.v1.SecurityOrBuilder> securityBuilder_;

    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public java.util.List<com.google.a2a.v1.Security> getSecurityList() {
      if (securityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(security_);
      } else {
        return securityBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public int getSecurityCount() {
      if (securityBuilder_ == null) {
        return security_.size();
      } else {
        return securityBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public com.google.a2a.v1.Security getSecurity(int index) {
      if (securityBuilder_ == null) {
        return security_.get(index);
      } else {
        return securityBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder setSecurity(
        int index, com.google.a2a.v1.Security value) {
      if (securityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityIsMutable();
        security_.set(index, value);
        onChanged();
      } else {
        securityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder setSecurity(
        int index, com.google.a2a.v1.Security.Builder builderForValue) {
      if (securityBuilder_ == null) {
        ensureSecurityIsMutable();
        security_.set(index, builderForValue.build());
        onChanged();
      } else {
        securityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder addSecurity(com.google.a2a.v1.Security value) {
      if (securityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityIsMutable();
        security_.add(value);
        onChanged();
      } else {
        securityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder addSecurity(
        int index, com.google.a2a.v1.Security value) {
      if (securityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityIsMutable();
        security_.add(index, value);
        onChanged();
      } else {
        securityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder addSecurity(
        com.google.a2a.v1.Security.Builder builderForValue) {
      if (securityBuilder_ == null) {
        ensureSecurityIsMutable();
        security_.add(builderForValue.build());
        onChanged();
      } else {
        securityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder addSecurity(
        int index, com.google.a2a.v1.Security.Builder builderForValue) {
      if (securityBuilder_ == null) {
        ensureSecurityIsMutable();
        security_.add(index, builderForValue.build());
        onChanged();
      } else {
        securityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder addAllSecurity(
        java.lang.Iterable<? extends com.google.a2a.v1.Security> values) {
      if (securityBuilder_ == null) {
        ensureSecurityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, security_);
        onChanged();
      } else {
        securityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder clearSecurity() {
      if (securityBuilder_ == null) {
        security_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        securityBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public Builder removeSecurity(int index) {
      if (securityBuilder_ == null) {
        ensureSecurityIsMutable();
        security_.remove(index);
        onChanged();
      } else {
        securityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public com.google.a2a.v1.Security.Builder getSecurityBuilder(
        int index) {
      return internalGetSecurityFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public com.google.a2a.v1.SecurityOrBuilder getSecurityOrBuilder(
        int index) {
      if (securityBuilder_ == null) {
        return security_.get(index);  } else {
        return securityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public java.util.List<? extends com.google.a2a.v1.SecurityOrBuilder> 
         getSecurityOrBuilderList() {
      if (securityBuilder_ != null) {
        return securityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(security_);
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public com.google.a2a.v1.Security.Builder addSecurityBuilder() {
      return internalGetSecurityFieldBuilder().addBuilder(
          com.google.a2a.v1.Security.getDefaultInstance());
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public com.google.a2a.v1.Security.Builder addSecurityBuilder(
        int index) {
      return internalGetSecurityFieldBuilder().addBuilder(
          index, com.google.a2a.v1.Security.getDefaultInstance());
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * Security schemes necessary for the agent to leverage this skill.
     * As in the overall AgentCard.security, this list represents a logical OR of
     * security requirement objects. Each object is a set of security schemes
     * that must be used together (a logical AND).
     * </pre>
     *
     * <code>repeated .a2a.v1.Security security = 8 [json_name = "security"];</code>
     */
    public java.util.List<com.google.a2a.v1.Security.Builder> 
         getSecurityBuilderList() {
      return internalGetSecurityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.a2a.v1.Security, com.google.a2a.v1.Security.Builder, com.google.a2a.v1.SecurityOrBuilder> 
        internalGetSecurityFieldBuilder() {
      if (securityBuilder_ == null) {
        securityBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.a2a.v1.Security, com.google.a2a.v1.Security.Builder, com.google.a2a.v1.SecurityOrBuilder>(
                security_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        security_ = null;
      }
      return securityBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.AgentSkill)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.AgentSkill)
  private static final com.google.a2a.v1.AgentSkill DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.a2a.v1.AgentSkill();
  }

  public static com.google.a2a.v1.AgentSkill getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentSkill>
      PARSER = new com.google.protobuf.AbstractParser<AgentSkill>() {
    @java.lang.Override
    public AgentSkill parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AgentSkill> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentSkill> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.a2a.v1.AgentSkill getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

