// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface AgentProviderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentProvider)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The providers reference url
   * Example: "https://ai.google.dev"
   * </pre>
   *
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * The providers reference url
   * Example: "https://ai.google.dev"
   * </pre>
   *
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * The providers organization name
   * Example: "Google"
   * </pre>
   *
   * <code>string organization = 2 [json_name = "organization"];</code>
   * @return The organization.
   */
  java.lang.String getOrganization();
  /**
   * <pre>
   * The providers organization name
   * Example: "Google"
   * </pre>
   *
   * <code>string organization = 2 [json_name = "organization"];</code>
   * @return The bytes for organization.
   */
  com.google.protobuf.ByteString
      getOrganizationBytes();
}
