// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface AgentExtensionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentExtension)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The URI of the extension.
   * Example: "https://developers.google.com/identity/protocols/oauth2"
   * </pre>
   *
   * <code>string uri = 1 [json_name = "uri"];</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * The URI of the extension.
   * Example: "https://developers.google.com/identity/protocols/oauth2"
   * </pre>
   *
   * <code>string uri = 1 [json_name = "uri"];</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <pre>
   * A description of how this agent uses this extension.
   * Example: "Google OAuth 2.0 authentication"
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * A description of how this agent uses this extension.
   * Example: "Google OAuth 2.0 authentication"
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Whether the client must follow specific requirements of the extension.
   * Example: false
   * </pre>
   *
   * <code>bool required = 3 [json_name = "required"];</code>
   * @return The required.
   */
  boolean getRequired();

  /**
   * <pre>
   * Optional configuration for the extension.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4 [json_name = "params"];</code>
   * @return Whether the params field is set.
   */
  boolean hasParams();
  /**
   * <pre>
   * Optional configuration for the extension.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4 [json_name = "params"];</code>
   * @return The params.
   */
  com.google.protobuf.Struct getParams();
  /**
   * <pre>
   * Optional configuration for the extension.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4 [json_name = "params"];</code>
   */
  com.google.protobuf.StructOrBuilder getParamsOrBuilder();
}
