// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface ArtifactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.Artifact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the artifact. It must be at least unique
   * within a task.
   * </pre>
   *
   * <code>string artifact_id = 1 [json_name = "artifactId"];</code>
   * @return The artifactId.
   */
  java.lang.String getArtifactId();
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the artifact. It must be at least unique
   * within a task.
   * </pre>
   *
   * <code>string artifact_id = 1 [json_name = "artifactId"];</code>
   * @return The bytes for artifactId.
   */
  com.google.protobuf.ByteString
      getArtifactIdBytes();

  /**
   * <pre>
   * A human readable name for the artifact.
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * A human readable name for the artifact.
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * A human readable description of the artifact, optional.
   * </pre>
   *
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * A human readable description of the artifact, optional.
   * </pre>
   *
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * The content of the artifact.
   * </pre>
   *
   * <code>repeated .a2a.v1.Part parts = 5 [json_name = "parts"];</code>
   */
  java.util.List<com.google.a2a.v1.Part> 
      getPartsList();
  /**
   * <pre>
   * The content of the artifact.
   * </pre>
   *
   * <code>repeated .a2a.v1.Part parts = 5 [json_name = "parts"];</code>
   */
  com.google.a2a.v1.Part getParts(int index);
  /**
   * <pre>
   * The content of the artifact.
   * </pre>
   *
   * <code>repeated .a2a.v1.Part parts = 5 [json_name = "parts"];</code>
   */
  int getPartsCount();
  /**
   * <pre>
   * The content of the artifact.
   * </pre>
   *
   * <code>repeated .a2a.v1.Part parts = 5 [json_name = "parts"];</code>
   */
  java.util.List<? extends com.google.a2a.v1.PartOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <pre>
   * The content of the artifact.
   * </pre>
   *
   * <code>repeated .a2a.v1.Part parts = 5 [json_name = "parts"];</code>
   */
  com.google.a2a.v1.PartOrBuilder getPartsOrBuilder(
      int index);

  /**
   * <pre>
   * Optional metadata included with the artifact.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Optional metadata included with the artifact.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * Optional metadata included with the artifact.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * The URIs of extensions that are present or contributed to this Artifact.
   * </pre>
   *
   * <code>repeated string extensions = 7 [json_name = "extensions"];</code>
   * @return A list containing the extensions.
   */
  java.util.List<java.lang.String>
      getExtensionsList();
  /**
   * <pre>
   * The URIs of extensions that are present or contributed to this Artifact.
   * </pre>
   *
   * <code>repeated string extensions = 7 [json_name = "extensions"];</code>
   * @return The count of extensions.
   */
  int getExtensionsCount();
  /**
   * <pre>
   * The URIs of extensions that are present or contributed to this Artifact.
   * </pre>
   *
   * <code>repeated string extensions = 7 [json_name = "extensions"];</code>
   * @param index The index of the element to return.
   * @return The extensions at the given index.
   */
  java.lang.String getExtensions(int index);
  /**
   * <pre>
   * The URIs of extensions that are present or contributed to this Artifact.
   * </pre>
   *
   * <code>repeated string extensions = 7 [json_name = "extensions"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the extensions at the given index.
   */
  com.google.protobuf.ByteString
      getExtensionsBytes(int index);
}
