// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface AuthenticationInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AuthenticationInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Supported authentication schemes - e.g. Basic, Bearer, etc
   * </pre>
   *
   * <code>repeated string schemes = 1 [json_name = "schemes"];</code>
   * @return A list containing the schemes.
   */
  java.util.List<java.lang.String>
      getSchemesList();
  /**
   * <pre>
   * Supported authentication schemes - e.g. Basic, Bearer, etc
   * </pre>
   *
   * <code>repeated string schemes = 1 [json_name = "schemes"];</code>
   * @return The count of schemes.
   */
  int getSchemesCount();
  /**
   * <pre>
   * Supported authentication schemes - e.g. Basic, Bearer, etc
   * </pre>
   *
   * <code>repeated string schemes = 1 [json_name = "schemes"];</code>
   * @param index The index of the element to return.
   * @return The schemes at the given index.
   */
  java.lang.String getSchemes(int index);
  /**
   * <pre>
   * Supported authentication schemes - e.g. Basic, Bearer, etc
   * </pre>
   *
   * <code>repeated string schemes = 1 [json_name = "schemes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the schemes at the given index.
   */
  com.google.protobuf.ByteString
      getSchemesBytes(int index);

  /**
   * <pre>
   * Optional credentials
   * </pre>
   *
   * <code>string credentials = 2 [json_name = "credentials"];</code>
   * @return The credentials.
   */
  java.lang.String getCredentials();
  /**
   * <pre>
   * Optional credentials
   * </pre>
   *
   * <code>string credentials = 2 [json_name = "credentials"];</code>
   * @return The bytes for credentials.
   */
  com.google.protobuf.ByteString
      getCredentialsBytes();
}
