// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

/**
 * <pre>
 * --8&lt;-- [start:SetTaskPushNotificationConfigRequest]
 * </pre>
 *
 * Protobuf type {@code a2a.v1.CreateTaskPushNotificationConfigRequest}
 */
@com.google.protobuf.Generated
public final class CreateTaskPushNotificationConfigRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.CreateTaskPushNotificationConfigRequest)
    CreateTaskPushNotificationConfigRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "CreateTaskPushNotificationConfigRequest");
  }
  // Use CreateTaskPushNotificationConfigRequest.newBuilder() to construct.
  private CreateTaskPushNotificationConfigRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateTaskPushNotificationConfigRequest() {
    parent_ = "";
    configId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.a2a.v1.CreateTaskPushNotificationConfigRequest.class, com.google.a2a.v1.CreateTaskPushNotificationConfigRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PARENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parent_ = "";
  /**
   * <pre>
   * The parent task resource for this config.
   * Format: tasks/{task_id}
   * </pre>
   *
   * <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The parent.
   */
  @java.lang.Override
  public java.lang.String getParent() {
    java.lang.Object ref = parent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The parent task resource for this config.
   * Format: tasks/{task_id}
   * </pre>
   *
   * <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for parent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentBytes() {
    java.lang.Object ref = parent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIG_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object configId_ = "";
  /**
   * <pre>
   * The ID for the new config.
   * </pre>
   *
   * <code>string config_id = 2 [json_name = "configId", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The configId.
   */
  @java.lang.Override
  public java.lang.String getConfigId() {
    java.lang.Object ref = configId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      configId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID for the new config.
   * </pre>
   *
   * <code>string config_id = 2 [json_name = "configId", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for configId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConfigIdBytes() {
    java.lang.Object ref = configId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      configId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIG_FIELD_NUMBER = 3;
  private com.google.a2a.v1.TaskPushNotificationConfig config_;
  /**
   * <pre>
   * The configuration to create.
   * </pre>
   *
   * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The configuration to create.
   * </pre>
   *
   * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The config.
   */
  @java.lang.Override
  public com.google.a2a.v1.TaskPushNotificationConfig getConfig() {
    return config_ == null ? com.google.a2a.v1.TaskPushNotificationConfig.getDefaultInstance() : config_;
  }
  /**
   * <pre>
   * The configuration to create.
   * </pre>
   *
   * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.TaskPushNotificationConfigOrBuilder getConfigOrBuilder() {
    return config_ == null ? com.google.a2a.v1.TaskPushNotificationConfig.getDefaultInstance() : config_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(parent_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, parent_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(configId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, configId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getConfig());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(parent_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, parent_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(configId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, configId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getConfig());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.a2a.v1.CreateTaskPushNotificationConfigRequest)) {
      return super.equals(obj);
    }
    com.google.a2a.v1.CreateTaskPushNotificationConfigRequest other = (com.google.a2a.v1.CreateTaskPushNotificationConfigRequest) obj;

    if (!getParent()
        .equals(other.getParent())) return false;
    if (!getConfigId()
        .equals(other.getConfigId())) return false;
    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARENT_FIELD_NUMBER;
    hash = (53 * hash) + getParent().hashCode();
    hash = (37 * hash) + CONFIG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConfigId().hashCode();
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.a2a.v1.CreateTaskPushNotificationConfigRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:SetTaskPushNotificationConfigRequest]
   * </pre>
   *
   * Protobuf type {@code a2a.v1.CreateTaskPushNotificationConfigRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.CreateTaskPushNotificationConfigRequest)
      com.google.a2a.v1.CreateTaskPushNotificationConfigRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.a2a.v1.CreateTaskPushNotificationConfigRequest.class, com.google.a2a.v1.CreateTaskPushNotificationConfigRequest.Builder.class);
    }

    // Construct using com.google.a2a.v1.CreateTaskPushNotificationConfigRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetConfigFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      parent_ = "";
      configId_ = "";
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor;
    }

    @java.lang.Override
    public com.google.a2a.v1.CreateTaskPushNotificationConfigRequest getDefaultInstanceForType() {
      return com.google.a2a.v1.CreateTaskPushNotificationConfigRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.a2a.v1.CreateTaskPushNotificationConfigRequest build() {
      com.google.a2a.v1.CreateTaskPushNotificationConfigRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.a2a.v1.CreateTaskPushNotificationConfigRequest buildPartial() {
      com.google.a2a.v1.CreateTaskPushNotificationConfigRequest result = new com.google.a2a.v1.CreateTaskPushNotificationConfigRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.a2a.v1.CreateTaskPushNotificationConfigRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.parent_ = parent_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.configId_ = configId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.config_ = configBuilder_ == null
            ? config_
            : configBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.a2a.v1.CreateTaskPushNotificationConfigRequest) {
        return mergeFrom((com.google.a2a.v1.CreateTaskPushNotificationConfigRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.a2a.v1.CreateTaskPushNotificationConfigRequest other) {
      if (other == com.google.a2a.v1.CreateTaskPushNotificationConfigRequest.getDefaultInstance()) return this;
      if (!other.getParent().isEmpty()) {
        parent_ = other.parent_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getConfigId().isEmpty()) {
        configId_ = other.configId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              parent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              configId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object parent_ = "";
    /**
     * <pre>
     * The parent task resource for this config.
     * Format: tasks/{task_id}
     * </pre>
     *
     * <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The parent.
     */
    public java.lang.String getParent() {
      java.lang.Object ref = parent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The parent task resource for this config.
     * Format: tasks/{task_id}
     * </pre>
     *
     * <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for parent.
     */
    public com.google.protobuf.ByteString
        getParentBytes() {
      java.lang.Object ref = parent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The parent task resource for this config.
     * Format: tasks/{task_id}
     * </pre>
     *
     * <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The parent to set.
     * @return This builder for chaining.
     */
    public Builder setParent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The parent task resource for this config.
     * Format: tasks/{task_id}
     * </pre>
     *
     * <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearParent() {
      parent_ = getDefaultInstance().getParent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The parent task resource for this config.
     * Format: tasks/{task_id}
     * </pre>
     *
     * <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for parent to set.
     * @return This builder for chaining.
     */
    public Builder setParentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object configId_ = "";
    /**
     * <pre>
     * The ID for the new config.
     * </pre>
     *
     * <code>string config_id = 2 [json_name = "configId", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The configId.
     */
    public java.lang.String getConfigId() {
      java.lang.Object ref = configId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID for the new config.
     * </pre>
     *
     * <code>string config_id = 2 [json_name = "configId", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for configId.
     */
    public com.google.protobuf.ByteString
        getConfigIdBytes() {
      java.lang.Object ref = configId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID for the new config.
     * </pre>
     *
     * <code>string config_id = 2 [json_name = "configId", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The configId to set.
     * @return This builder for chaining.
     */
    public Builder setConfigId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      configId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID for the new config.
     * </pre>
     *
     * <code>string config_id = 2 [json_name = "configId", (.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearConfigId() {
      configId_ = getDefaultInstance().getConfigId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID for the new config.
     * </pre>
     *
     * <code>string config_id = 2 [json_name = "configId", (.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for configId to set.
     * @return This builder for chaining.
     */
    public Builder setConfigIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      configId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.a2a.v1.TaskPushNotificationConfig config_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.TaskPushNotificationConfig, com.google.a2a.v1.TaskPushNotificationConfig.Builder, com.google.a2a.v1.TaskPushNotificationConfigOrBuilder> configBuilder_;
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The config.
     */
    public com.google.a2a.v1.TaskPushNotificationConfig getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? com.google.a2a.v1.TaskPushNotificationConfig.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setConfig(com.google.a2a.v1.TaskPushNotificationConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
      } else {
        configBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setConfig(
        com.google.a2a.v1.TaskPushNotificationConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeConfig(com.google.a2a.v1.TaskPushNotificationConfig value) {
      if (configBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          config_ != null &&
          config_ != com.google.a2a.v1.TaskPushNotificationConfig.getDefaultInstance()) {
          getConfigBuilder().mergeFrom(value);
        } else {
          config_ = value;
        }
      } else {
        configBuilder_.mergeFrom(value);
      }
      if (config_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearConfig() {
      bitField0_ = (bitField0_ & ~0x00000004);
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.a2a.v1.TaskPushNotificationConfig.Builder getConfigBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.a2a.v1.TaskPushNotificationConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            com.google.a2a.v1.TaskPushNotificationConfig.getDefaultInstance() : config_;
      }
    }
    /**
     * <pre>
     * The configuration to create.
     * </pre>
     *
     * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [json_name = "config", (.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.TaskPushNotificationConfig, com.google.a2a.v1.TaskPushNotificationConfig.Builder, com.google.a2a.v1.TaskPushNotificationConfigOrBuilder> 
        internalGetConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.TaskPushNotificationConfig, com.google.a2a.v1.TaskPushNotificationConfig.Builder, com.google.a2a.v1.TaskPushNotificationConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.CreateTaskPushNotificationConfigRequest)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.CreateTaskPushNotificationConfigRequest)
  private static final com.google.a2a.v1.CreateTaskPushNotificationConfigRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.a2a.v1.CreateTaskPushNotificationConfigRequest();
  }

  public static com.google.a2a.v1.CreateTaskPushNotificationConfigRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTaskPushNotificationConfigRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateTaskPushNotificationConfigRequest>() {
    @java.lang.Override
    public CreateTaskPushNotificationConfigRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateTaskPushNotificationConfigRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTaskPushNotificationConfigRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.a2a.v1.CreateTaskPushNotificationConfigRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

