// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface FilePartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.FilePart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
   * @return Whether the fileWithUri field is set.
   */
  boolean hasFileWithUri();
  /**
   * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
   * @return The fileWithUri.
   */
  java.lang.String getFileWithUri();
  /**
   * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
   * @return The bytes for fileWithUri.
   */
  com.google.protobuf.ByteString
      getFileWithUriBytes();

  /**
   * <code>bytes file_with_bytes = 2 [json_name = "fileWithBytes"];</code>
   * @return Whether the fileWithBytes field is set.
   */
  boolean hasFileWithBytes();
  /**
   * <code>bytes file_with_bytes = 2 [json_name = "fileWithBytes"];</code>
   * @return The fileWithBytes.
   */
  com.google.protobuf.ByteString getFileWithBytes();

  /**
   * <code>string mime_type = 3 [json_name = "mimeType"];</code>
   * @return The mimeType.
   */
  java.lang.String getMimeType();
  /**
   * <code>string mime_type = 3 [json_name = "mimeType"];</code>
   * @return The bytes for mimeType.
   */
  com.google.protobuf.ByteString
      getMimeTypeBytes();

  /**
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  com.google.a2a.v1.FilePart.FileCase getFileCase();
}
