// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface GetAgentCardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.GetAgentCardRequest)
    com.google.protobuf.MessageOrBuilder {
}
