// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

/**
 * <pre>
 * --8&lt;-- [start:HTTPAuthSecurityScheme]
 * </pre>
 *
 * Protobuf type {@code a2a.v1.HTTPAuthSecurityScheme}
 */
@com.google.protobuf.Generated
public final class HTTPAuthSecurityScheme extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.HTTPAuthSecurityScheme)
    HTTPAuthSecuritySchemeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "HTTPAuthSecurityScheme");
  }
  // Use HTTPAuthSecurityScheme.newBuilder() to construct.
  private HTTPAuthSecurityScheme(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HTTPAuthSecurityScheme() {
    description_ = "";
    scheme_ = "";
    bearerFormat_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_HTTPAuthSecurityScheme_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.a2a.v1.HTTPAuthSecurityScheme.class, com.google.a2a.v1.HTTPAuthSecurityScheme.Builder.class);
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHEME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scheme_ = "";
  /**
   * <pre>
   * The name of the HTTP Authentication scheme to be used in the
   * Authorization header as defined in RFC7235. The values used SHOULD be
   * registered in the IANA Authentication Scheme registry.
   * The value is case-insensitive, as defined in RFC7235.
   * </pre>
   *
   * <code>string scheme = 2 [json_name = "scheme"];</code>
   * @return The scheme.
   */
  @java.lang.Override
  public java.lang.String getScheme() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scheme_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the HTTP Authentication scheme to be used in the
   * Authorization header as defined in RFC7235. The values used SHOULD be
   * registered in the IANA Authentication Scheme registry.
   * The value is case-insensitive, as defined in RFC7235.
   * </pre>
   *
   * <code>string scheme = 2 [json_name = "scheme"];</code>
   * @return The bytes for scheme.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemeBytes() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scheme_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BEARER_FORMAT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bearerFormat_ = "";
  /**
   * <pre>
   * A hint to the client to identify how the bearer token is formatted.
   * Bearer tokens are usually generated by an authorization server, so
   * this information is primarily for documentation purposes.
   * </pre>
   *
   * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
   * @return The bearerFormat.
   */
  @java.lang.Override
  public java.lang.String getBearerFormat() {
    java.lang.Object ref = bearerFormat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bearerFormat_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A hint to the client to identify how the bearer token is formatted.
   * Bearer tokens are usually generated by an authorization server, so
   * this information is primarily for documentation purposes.
   * </pre>
   *
   * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
   * @return The bytes for bearerFormat.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBearerFormatBytes() {
    java.lang.Object ref = bearerFormat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bearerFormat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scheme_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, scheme_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bearerFormat_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, bearerFormat_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scheme_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, scheme_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bearerFormat_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, bearerFormat_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.a2a.v1.HTTPAuthSecurityScheme)) {
      return super.equals(obj);
    }
    com.google.a2a.v1.HTTPAuthSecurityScheme other = (com.google.a2a.v1.HTTPAuthSecurityScheme) obj;

    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getScheme()
        .equals(other.getScheme())) return false;
    if (!getBearerFormat()
        .equals(other.getBearerFormat())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + SCHEME_FIELD_NUMBER;
    hash = (53 * hash) + getScheme().hashCode();
    hash = (37 * hash) + BEARER_FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getBearerFormat().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.HTTPAuthSecurityScheme parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.a2a.v1.HTTPAuthSecurityScheme prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:HTTPAuthSecurityScheme]
   * </pre>
   *
   * Protobuf type {@code a2a.v1.HTTPAuthSecurityScheme}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.HTTPAuthSecurityScheme)
      com.google.a2a.v1.HTTPAuthSecuritySchemeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_HTTPAuthSecurityScheme_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.a2a.v1.HTTPAuthSecurityScheme.class, com.google.a2a.v1.HTTPAuthSecurityScheme.Builder.class);
    }

    // Construct using com.google.a2a.v1.HTTPAuthSecurityScheme.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      description_ = "";
      scheme_ = "";
      bearerFormat_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor;
    }

    @java.lang.Override
    public com.google.a2a.v1.HTTPAuthSecurityScheme getDefaultInstanceForType() {
      return com.google.a2a.v1.HTTPAuthSecurityScheme.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.a2a.v1.HTTPAuthSecurityScheme build() {
      com.google.a2a.v1.HTTPAuthSecurityScheme result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.a2a.v1.HTTPAuthSecurityScheme buildPartial() {
      com.google.a2a.v1.HTTPAuthSecurityScheme result = new com.google.a2a.v1.HTTPAuthSecurityScheme(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.a2a.v1.HTTPAuthSecurityScheme result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.scheme_ = scheme_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bearerFormat_ = bearerFormat_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.a2a.v1.HTTPAuthSecurityScheme) {
        return mergeFrom((com.google.a2a.v1.HTTPAuthSecurityScheme)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.a2a.v1.HTTPAuthSecurityScheme other) {
      if (other == com.google.a2a.v1.HTTPAuthSecurityScheme.getDefaultInstance()) return this;
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getScheme().isEmpty()) {
        scheme_ = other.scheme_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBearerFormat().isEmpty()) {
        bearerFormat_ = other.bearerFormat_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              scheme_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              bearerFormat_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object scheme_ = "";
    /**
     * <pre>
     * The name of the HTTP Authentication scheme to be used in the
     * Authorization header as defined in RFC7235. The values used SHOULD be
     * registered in the IANA Authentication Scheme registry.
     * The value is case-insensitive, as defined in RFC7235.
     * </pre>
     *
     * <code>string scheme = 2 [json_name = "scheme"];</code>
     * @return The scheme.
     */
    public java.lang.String getScheme() {
      java.lang.Object ref = scheme_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheme_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the HTTP Authentication scheme to be used in the
     * Authorization header as defined in RFC7235. The values used SHOULD be
     * registered in the IANA Authentication Scheme registry.
     * The value is case-insensitive, as defined in RFC7235.
     * </pre>
     *
     * <code>string scheme = 2 [json_name = "scheme"];</code>
     * @return The bytes for scheme.
     */
    public com.google.protobuf.ByteString
        getSchemeBytes() {
      java.lang.Object ref = scheme_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scheme_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the HTTP Authentication scheme to be used in the
     * Authorization header as defined in RFC7235. The values used SHOULD be
     * registered in the IANA Authentication Scheme registry.
     * The value is case-insensitive, as defined in RFC7235.
     * </pre>
     *
     * <code>string scheme = 2 [json_name = "scheme"];</code>
     * @param value The scheme to set.
     * @return This builder for chaining.
     */
    public Builder setScheme(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scheme_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the HTTP Authentication scheme to be used in the
     * Authorization header as defined in RFC7235. The values used SHOULD be
     * registered in the IANA Authentication Scheme registry.
     * The value is case-insensitive, as defined in RFC7235.
     * </pre>
     *
     * <code>string scheme = 2 [json_name = "scheme"];</code>
     * @return This builder for chaining.
     */
    public Builder clearScheme() {
      scheme_ = getDefaultInstance().getScheme();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the HTTP Authentication scheme to be used in the
     * Authorization header as defined in RFC7235. The values used SHOULD be
     * registered in the IANA Authentication Scheme registry.
     * The value is case-insensitive, as defined in RFC7235.
     * </pre>
     *
     * <code>string scheme = 2 [json_name = "scheme"];</code>
     * @param value The bytes for scheme to set.
     * @return This builder for chaining.
     */
    public Builder setSchemeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scheme_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object bearerFormat_ = "";
    /**
     * <pre>
     * A hint to the client to identify how the bearer token is formatted.
     * Bearer tokens are usually generated by an authorization server, so
     * this information is primarily for documentation purposes.
     * </pre>
     *
     * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
     * @return The bearerFormat.
     */
    public java.lang.String getBearerFormat() {
      java.lang.Object ref = bearerFormat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bearerFormat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A hint to the client to identify how the bearer token is formatted.
     * Bearer tokens are usually generated by an authorization server, so
     * this information is primarily for documentation purposes.
     * </pre>
     *
     * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
     * @return The bytes for bearerFormat.
     */
    public com.google.protobuf.ByteString
        getBearerFormatBytes() {
      java.lang.Object ref = bearerFormat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bearerFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A hint to the client to identify how the bearer token is formatted.
     * Bearer tokens are usually generated by an authorization server, so
     * this information is primarily for documentation purposes.
     * </pre>
     *
     * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
     * @param value The bearerFormat to set.
     * @return This builder for chaining.
     */
    public Builder setBearerFormat(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bearerFormat_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A hint to the client to identify how the bearer token is formatted.
     * Bearer tokens are usually generated by an authorization server, so
     * this information is primarily for documentation purposes.
     * </pre>
     *
     * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBearerFormat() {
      bearerFormat_ = getDefaultInstance().getBearerFormat();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A hint to the client to identify how the bearer token is formatted.
     * Bearer tokens are usually generated by an authorization server, so
     * this information is primarily for documentation purposes.
     * </pre>
     *
     * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
     * @param value The bytes for bearerFormat to set.
     * @return This builder for chaining.
     */
    public Builder setBearerFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bearerFormat_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.HTTPAuthSecurityScheme)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.HTTPAuthSecurityScheme)
  private static final com.google.a2a.v1.HTTPAuthSecurityScheme DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.a2a.v1.HTTPAuthSecurityScheme();
  }

  public static com.google.a2a.v1.HTTPAuthSecurityScheme getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HTTPAuthSecurityScheme>
      PARSER = new com.google.protobuf.AbstractParser<HTTPAuthSecurityScheme>() {
    @java.lang.Override
    public HTTPAuthSecurityScheme parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HTTPAuthSecurityScheme> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HTTPAuthSecurityScheme> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.a2a.v1.HTTPAuthSecurityScheme getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

