// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface HTTPAuthSecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.HTTPAuthSecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * The name of the HTTP Authentication scheme to be used in the
   * Authorization header as defined in RFC7235. The values used SHOULD be
   * registered in the IANA Authentication Scheme registry.
   * The value is case-insensitive, as defined in RFC7235.
   * </pre>
   *
   * <code>string scheme = 2 [json_name = "scheme"];</code>
   * @return The scheme.
   */
  java.lang.String getScheme();
  /**
   * <pre>
   * The name of the HTTP Authentication scheme to be used in the
   * Authorization header as defined in RFC7235. The values used SHOULD be
   * registered in the IANA Authentication Scheme registry.
   * The value is case-insensitive, as defined in RFC7235.
   * </pre>
   *
   * <code>string scheme = 2 [json_name = "scheme"];</code>
   * @return The bytes for scheme.
   */
  com.google.protobuf.ByteString
      getSchemeBytes();

  /**
   * <pre>
   * A hint to the client to identify how the bearer token is formatted.
   * Bearer tokens are usually generated by an authorization server, so
   * this information is primarily for documentation purposes.
   * </pre>
   *
   * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
   * @return The bearerFormat.
   */
  java.lang.String getBearerFormat();
  /**
   * <pre>
   * A hint to the client to identify how the bearer token is formatted.
   * Bearer tokens are usually generated by an authorization server, so
   * this information is primarily for documentation purposes.
   * </pre>
   *
   * <code>string bearer_format = 3 [json_name = "bearerFormat"];</code>
   * @return The bytes for bearerFormat.
   */
  com.google.protobuf.ByteString
      getBearerFormatBytes();
}
