// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

/**
 * <pre>
 * --8&lt;-- [start:OAuthFlows]
 * </pre>
 *
 * Protobuf type {@code a2a.v1.OAuthFlows}
 */
@com.google.protobuf.Generated
public final class OAuthFlows extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.OAuthFlows)
    OAuthFlowsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "OAuthFlows");
  }
  // Use OAuthFlows.newBuilder() to construct.
  private OAuthFlows(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OAuthFlows() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_OAuthFlows_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_OAuthFlows_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.a2a.v1.OAuthFlows.class, com.google.a2a.v1.OAuthFlows.Builder.class);
  }

  private int flowCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object flow_;
  public enum FlowCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    AUTHORIZATION_CODE(1),
    CLIENT_CREDENTIALS(2),
    IMPLICIT(3),
    PASSWORD(4),
    FLOW_NOT_SET(0);
    private final int value;
    private FlowCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FlowCase valueOf(int value) {
      return forNumber(value);
    }

    public static FlowCase forNumber(int value) {
      switch (value) {
        case 1: return AUTHORIZATION_CODE;
        case 2: return CLIENT_CREDENTIALS;
        case 3: return IMPLICIT;
        case 4: return PASSWORD;
        case 0: return FLOW_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FlowCase
  getFlowCase() {
    return FlowCase.forNumber(
        flowCase_);
  }

  public static final int AUTHORIZATION_CODE_FIELD_NUMBER = 1;
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
   * @return Whether the authorizationCode field is set.
   */
  @java.lang.Override
  public boolean hasAuthorizationCode() {
    return flowCase_ == 1;
  }
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
   * @return The authorizationCode.
   */
  @java.lang.Override
  public com.google.a2a.v1.AuthorizationCodeOAuthFlow getAuthorizationCode() {
    if (flowCase_ == 1) {
       return (com.google.a2a.v1.AuthorizationCodeOAuthFlow) flow_;
    }
    return com.google.a2a.v1.AuthorizationCodeOAuthFlow.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.AuthorizationCodeOAuthFlowOrBuilder getAuthorizationCodeOrBuilder() {
    if (flowCase_ == 1) {
       return (com.google.a2a.v1.AuthorizationCodeOAuthFlow) flow_;
    }
    return com.google.a2a.v1.AuthorizationCodeOAuthFlow.getDefaultInstance();
  }

  public static final int CLIENT_CREDENTIALS_FIELD_NUMBER = 2;
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
   * @return Whether the clientCredentials field is set.
   */
  @java.lang.Override
  public boolean hasClientCredentials() {
    return flowCase_ == 2;
  }
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
   * @return The clientCredentials.
   */
  @java.lang.Override
  public com.google.a2a.v1.ClientCredentialsOAuthFlow getClientCredentials() {
    if (flowCase_ == 2) {
       return (com.google.a2a.v1.ClientCredentialsOAuthFlow) flow_;
    }
    return com.google.a2a.v1.ClientCredentialsOAuthFlow.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.ClientCredentialsOAuthFlowOrBuilder getClientCredentialsOrBuilder() {
    if (flowCase_ == 2) {
       return (com.google.a2a.v1.ClientCredentialsOAuthFlow) flow_;
    }
    return com.google.a2a.v1.ClientCredentialsOAuthFlow.getDefaultInstance();
  }

  public static final int IMPLICIT_FIELD_NUMBER = 3;
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
   * @return Whether the implicit field is set.
   */
  @java.lang.Override
  public boolean hasImplicit() {
    return flowCase_ == 3;
  }
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
   * @return The implicit.
   */
  @java.lang.Override
  public com.google.a2a.v1.ImplicitOAuthFlow getImplicit() {
    if (flowCase_ == 3) {
       return (com.google.a2a.v1.ImplicitOAuthFlow) flow_;
    }
    return com.google.a2a.v1.ImplicitOAuthFlow.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.ImplicitOAuthFlowOrBuilder getImplicitOrBuilder() {
    if (flowCase_ == 3) {
       return (com.google.a2a.v1.ImplicitOAuthFlow) flow_;
    }
    return com.google.a2a.v1.ImplicitOAuthFlow.getDefaultInstance();
  }

  public static final int PASSWORD_FIELD_NUMBER = 4;
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
   * @return Whether the password field is set.
   */
  @java.lang.Override
  public boolean hasPassword() {
    return flowCase_ == 4;
  }
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
   * @return The password.
   */
  @java.lang.Override
  public com.google.a2a.v1.PasswordOAuthFlow getPassword() {
    if (flowCase_ == 4) {
       return (com.google.a2a.v1.PasswordOAuthFlow) flow_;
    }
    return com.google.a2a.v1.PasswordOAuthFlow.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.PasswordOAuthFlowOrBuilder getPasswordOrBuilder() {
    if (flowCase_ == 4) {
       return (com.google.a2a.v1.PasswordOAuthFlow) flow_;
    }
    return com.google.a2a.v1.PasswordOAuthFlow.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (flowCase_ == 1) {
      output.writeMessage(1, (com.google.a2a.v1.AuthorizationCodeOAuthFlow) flow_);
    }
    if (flowCase_ == 2) {
      output.writeMessage(2, (com.google.a2a.v1.ClientCredentialsOAuthFlow) flow_);
    }
    if (flowCase_ == 3) {
      output.writeMessage(3, (com.google.a2a.v1.ImplicitOAuthFlow) flow_);
    }
    if (flowCase_ == 4) {
      output.writeMessage(4, (com.google.a2a.v1.PasswordOAuthFlow) flow_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (flowCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.google.a2a.v1.AuthorizationCodeOAuthFlow) flow_);
    }
    if (flowCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.google.a2a.v1.ClientCredentialsOAuthFlow) flow_);
    }
    if (flowCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.google.a2a.v1.ImplicitOAuthFlow) flow_);
    }
    if (flowCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.google.a2a.v1.PasswordOAuthFlow) flow_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.a2a.v1.OAuthFlows)) {
      return super.equals(obj);
    }
    com.google.a2a.v1.OAuthFlows other = (com.google.a2a.v1.OAuthFlows) obj;

    if (!getFlowCase().equals(other.getFlowCase())) return false;
    switch (flowCase_) {
      case 1:
        if (!getAuthorizationCode()
            .equals(other.getAuthorizationCode())) return false;
        break;
      case 2:
        if (!getClientCredentials()
            .equals(other.getClientCredentials())) return false;
        break;
      case 3:
        if (!getImplicit()
            .equals(other.getImplicit())) return false;
        break;
      case 4:
        if (!getPassword()
            .equals(other.getPassword())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (flowCase_) {
      case 1:
        hash = (37 * hash) + AUTHORIZATION_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorizationCode().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CLIENT_CREDENTIALS_FIELD_NUMBER;
        hash = (53 * hash) + getClientCredentials().hashCode();
        break;
      case 3:
        hash = (37 * hash) + IMPLICIT_FIELD_NUMBER;
        hash = (53 * hash) + getImplicit().hashCode();
        break;
      case 4:
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.a2a.v1.OAuthFlows parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.a2a.v1.OAuthFlows parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.a2a.v1.OAuthFlows parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.OAuthFlows parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.a2a.v1.OAuthFlows prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:OAuthFlows]
   * </pre>
   *
   * Protobuf type {@code a2a.v1.OAuthFlows}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.OAuthFlows)
      com.google.a2a.v1.OAuthFlowsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_OAuthFlows_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_OAuthFlows_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.a2a.v1.OAuthFlows.class, com.google.a2a.v1.OAuthFlows.Builder.class);
    }

    // Construct using com.google.a2a.v1.OAuthFlows.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (authorizationCodeBuilder_ != null) {
        authorizationCodeBuilder_.clear();
      }
      if (clientCredentialsBuilder_ != null) {
        clientCredentialsBuilder_.clear();
      }
      if (implicitBuilder_ != null) {
        implicitBuilder_.clear();
      }
      if (passwordBuilder_ != null) {
        passwordBuilder_.clear();
      }
      flowCase_ = 0;
      flow_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_OAuthFlows_descriptor;
    }

    @java.lang.Override
    public com.google.a2a.v1.OAuthFlows getDefaultInstanceForType() {
      return com.google.a2a.v1.OAuthFlows.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.a2a.v1.OAuthFlows build() {
      com.google.a2a.v1.OAuthFlows result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.a2a.v1.OAuthFlows buildPartial() {
      com.google.a2a.v1.OAuthFlows result = new com.google.a2a.v1.OAuthFlows(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.a2a.v1.OAuthFlows result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.google.a2a.v1.OAuthFlows result) {
      result.flowCase_ = flowCase_;
      result.flow_ = this.flow_;
      if (flowCase_ == 1 &&
          authorizationCodeBuilder_ != null) {
        result.flow_ = authorizationCodeBuilder_.build();
      }
      if (flowCase_ == 2 &&
          clientCredentialsBuilder_ != null) {
        result.flow_ = clientCredentialsBuilder_.build();
      }
      if (flowCase_ == 3 &&
          implicitBuilder_ != null) {
        result.flow_ = implicitBuilder_.build();
      }
      if (flowCase_ == 4 &&
          passwordBuilder_ != null) {
        result.flow_ = passwordBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.a2a.v1.OAuthFlows) {
        return mergeFrom((com.google.a2a.v1.OAuthFlows)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.a2a.v1.OAuthFlows other) {
      if (other == com.google.a2a.v1.OAuthFlows.getDefaultInstance()) return this;
      switch (other.getFlowCase()) {
        case AUTHORIZATION_CODE: {
          mergeAuthorizationCode(other.getAuthorizationCode());
          break;
        }
        case CLIENT_CREDENTIALS: {
          mergeClientCredentials(other.getClientCredentials());
          break;
        }
        case IMPLICIT: {
          mergeImplicit(other.getImplicit());
          break;
        }
        case PASSWORD: {
          mergePassword(other.getPassword());
          break;
        }
        case FLOW_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetAuthorizationCodeFieldBuilder().getBuilder(),
                  extensionRegistry);
              flowCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetClientCredentialsFieldBuilder().getBuilder(),
                  extensionRegistry);
              flowCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetImplicitFieldBuilder().getBuilder(),
                  extensionRegistry);
              flowCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetPasswordFieldBuilder().getBuilder(),
                  extensionRegistry);
              flowCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int flowCase_ = 0;
    private java.lang.Object flow_;
    public FlowCase
        getFlowCase() {
      return FlowCase.forNumber(
          flowCase_);
    }

    public Builder clearFlow() {
      flowCase_ = 0;
      flow_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.AuthorizationCodeOAuthFlow, com.google.a2a.v1.AuthorizationCodeOAuthFlow.Builder, com.google.a2a.v1.AuthorizationCodeOAuthFlowOrBuilder> authorizationCodeBuilder_;
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     * @return Whether the authorizationCode field is set.
     */
    @java.lang.Override
    public boolean hasAuthorizationCode() {
      return flowCase_ == 1;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     * @return The authorizationCode.
     */
    @java.lang.Override
    public com.google.a2a.v1.AuthorizationCodeOAuthFlow getAuthorizationCode() {
      if (authorizationCodeBuilder_ == null) {
        if (flowCase_ == 1) {
          return (com.google.a2a.v1.AuthorizationCodeOAuthFlow) flow_;
        }
        return com.google.a2a.v1.AuthorizationCodeOAuthFlow.getDefaultInstance();
      } else {
        if (flowCase_ == 1) {
          return authorizationCodeBuilder_.getMessage();
        }
        return com.google.a2a.v1.AuthorizationCodeOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     */
    public Builder setAuthorizationCode(com.google.a2a.v1.AuthorizationCodeOAuthFlow value) {
      if (authorizationCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flow_ = value;
        onChanged();
      } else {
        authorizationCodeBuilder_.setMessage(value);
      }
      flowCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     */
    public Builder setAuthorizationCode(
        com.google.a2a.v1.AuthorizationCodeOAuthFlow.Builder builderForValue) {
      if (authorizationCodeBuilder_ == null) {
        flow_ = builderForValue.build();
        onChanged();
      } else {
        authorizationCodeBuilder_.setMessage(builderForValue.build());
      }
      flowCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     */
    public Builder mergeAuthorizationCode(com.google.a2a.v1.AuthorizationCodeOAuthFlow value) {
      if (authorizationCodeBuilder_ == null) {
        if (flowCase_ == 1 &&
            flow_ != com.google.a2a.v1.AuthorizationCodeOAuthFlow.getDefaultInstance()) {
          flow_ = com.google.a2a.v1.AuthorizationCodeOAuthFlow.newBuilder((com.google.a2a.v1.AuthorizationCodeOAuthFlow) flow_)
              .mergeFrom(value).buildPartial();
        } else {
          flow_ = value;
        }
        onChanged();
      } else {
        if (flowCase_ == 1) {
          authorizationCodeBuilder_.mergeFrom(value);
        } else {
          authorizationCodeBuilder_.setMessage(value);
        }
      }
      flowCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     */
    public Builder clearAuthorizationCode() {
      if (authorizationCodeBuilder_ == null) {
        if (flowCase_ == 1) {
          flowCase_ = 0;
          flow_ = null;
          onChanged();
        }
      } else {
        if (flowCase_ == 1) {
          flowCase_ = 0;
          flow_ = null;
        }
        authorizationCodeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     */
    public com.google.a2a.v1.AuthorizationCodeOAuthFlow.Builder getAuthorizationCodeBuilder() {
      return internalGetAuthorizationCodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     */
    @java.lang.Override
    public com.google.a2a.v1.AuthorizationCodeOAuthFlowOrBuilder getAuthorizationCodeOrBuilder() {
      if ((flowCase_ == 1) && (authorizationCodeBuilder_ != null)) {
        return authorizationCodeBuilder_.getMessageOrBuilder();
      } else {
        if (flowCase_ == 1) {
          return (com.google.a2a.v1.AuthorizationCodeOAuthFlow) flow_;
        }
        return com.google.a2a.v1.AuthorizationCodeOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.AuthorizationCodeOAuthFlow, com.google.a2a.v1.AuthorizationCodeOAuthFlow.Builder, com.google.a2a.v1.AuthorizationCodeOAuthFlowOrBuilder> 
        internalGetAuthorizationCodeFieldBuilder() {
      if (authorizationCodeBuilder_ == null) {
        if (!(flowCase_ == 1)) {
          flow_ = com.google.a2a.v1.AuthorizationCodeOAuthFlow.getDefaultInstance();
        }
        authorizationCodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.AuthorizationCodeOAuthFlow, com.google.a2a.v1.AuthorizationCodeOAuthFlow.Builder, com.google.a2a.v1.AuthorizationCodeOAuthFlowOrBuilder>(
                (com.google.a2a.v1.AuthorizationCodeOAuthFlow) flow_,
                getParentForChildren(),
                isClean());
        flow_ = null;
      }
      flowCase_ = 1;
      onChanged();
      return authorizationCodeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.ClientCredentialsOAuthFlow, com.google.a2a.v1.ClientCredentialsOAuthFlow.Builder, com.google.a2a.v1.ClientCredentialsOAuthFlowOrBuilder> clientCredentialsBuilder_;
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     * @return Whether the clientCredentials field is set.
     */
    @java.lang.Override
    public boolean hasClientCredentials() {
      return flowCase_ == 2;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     * @return The clientCredentials.
     */
    @java.lang.Override
    public com.google.a2a.v1.ClientCredentialsOAuthFlow getClientCredentials() {
      if (clientCredentialsBuilder_ == null) {
        if (flowCase_ == 2) {
          return (com.google.a2a.v1.ClientCredentialsOAuthFlow) flow_;
        }
        return com.google.a2a.v1.ClientCredentialsOAuthFlow.getDefaultInstance();
      } else {
        if (flowCase_ == 2) {
          return clientCredentialsBuilder_.getMessage();
        }
        return com.google.a2a.v1.ClientCredentialsOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     */
    public Builder setClientCredentials(com.google.a2a.v1.ClientCredentialsOAuthFlow value) {
      if (clientCredentialsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flow_ = value;
        onChanged();
      } else {
        clientCredentialsBuilder_.setMessage(value);
      }
      flowCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     */
    public Builder setClientCredentials(
        com.google.a2a.v1.ClientCredentialsOAuthFlow.Builder builderForValue) {
      if (clientCredentialsBuilder_ == null) {
        flow_ = builderForValue.build();
        onChanged();
      } else {
        clientCredentialsBuilder_.setMessage(builderForValue.build());
      }
      flowCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     */
    public Builder mergeClientCredentials(com.google.a2a.v1.ClientCredentialsOAuthFlow value) {
      if (clientCredentialsBuilder_ == null) {
        if (flowCase_ == 2 &&
            flow_ != com.google.a2a.v1.ClientCredentialsOAuthFlow.getDefaultInstance()) {
          flow_ = com.google.a2a.v1.ClientCredentialsOAuthFlow.newBuilder((com.google.a2a.v1.ClientCredentialsOAuthFlow) flow_)
              .mergeFrom(value).buildPartial();
        } else {
          flow_ = value;
        }
        onChanged();
      } else {
        if (flowCase_ == 2) {
          clientCredentialsBuilder_.mergeFrom(value);
        } else {
          clientCredentialsBuilder_.setMessage(value);
        }
      }
      flowCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     */
    public Builder clearClientCredentials() {
      if (clientCredentialsBuilder_ == null) {
        if (flowCase_ == 2) {
          flowCase_ = 0;
          flow_ = null;
          onChanged();
        }
      } else {
        if (flowCase_ == 2) {
          flowCase_ = 0;
          flow_ = null;
        }
        clientCredentialsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     */
    public com.google.a2a.v1.ClientCredentialsOAuthFlow.Builder getClientCredentialsBuilder() {
      return internalGetClientCredentialsFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     */
    @java.lang.Override
    public com.google.a2a.v1.ClientCredentialsOAuthFlowOrBuilder getClientCredentialsOrBuilder() {
      if ((flowCase_ == 2) && (clientCredentialsBuilder_ != null)) {
        return clientCredentialsBuilder_.getMessageOrBuilder();
      } else {
        if (flowCase_ == 2) {
          return (com.google.a2a.v1.ClientCredentialsOAuthFlow) flow_;
        }
        return com.google.a2a.v1.ClientCredentialsOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.ClientCredentialsOAuthFlow, com.google.a2a.v1.ClientCredentialsOAuthFlow.Builder, com.google.a2a.v1.ClientCredentialsOAuthFlowOrBuilder> 
        internalGetClientCredentialsFieldBuilder() {
      if (clientCredentialsBuilder_ == null) {
        if (!(flowCase_ == 2)) {
          flow_ = com.google.a2a.v1.ClientCredentialsOAuthFlow.getDefaultInstance();
        }
        clientCredentialsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.ClientCredentialsOAuthFlow, com.google.a2a.v1.ClientCredentialsOAuthFlow.Builder, com.google.a2a.v1.ClientCredentialsOAuthFlowOrBuilder>(
                (com.google.a2a.v1.ClientCredentialsOAuthFlow) flow_,
                getParentForChildren(),
                isClean());
        flow_ = null;
      }
      flowCase_ = 2;
      onChanged();
      return clientCredentialsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.ImplicitOAuthFlow, com.google.a2a.v1.ImplicitOAuthFlow.Builder, com.google.a2a.v1.ImplicitOAuthFlowOrBuilder> implicitBuilder_;
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     * @return Whether the implicit field is set.
     */
    @java.lang.Override
    public boolean hasImplicit() {
      return flowCase_ == 3;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     * @return The implicit.
     */
    @java.lang.Override
    public com.google.a2a.v1.ImplicitOAuthFlow getImplicit() {
      if (implicitBuilder_ == null) {
        if (flowCase_ == 3) {
          return (com.google.a2a.v1.ImplicitOAuthFlow) flow_;
        }
        return com.google.a2a.v1.ImplicitOAuthFlow.getDefaultInstance();
      } else {
        if (flowCase_ == 3) {
          return implicitBuilder_.getMessage();
        }
        return com.google.a2a.v1.ImplicitOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     */
    public Builder setImplicit(com.google.a2a.v1.ImplicitOAuthFlow value) {
      if (implicitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flow_ = value;
        onChanged();
      } else {
        implicitBuilder_.setMessage(value);
      }
      flowCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     */
    public Builder setImplicit(
        com.google.a2a.v1.ImplicitOAuthFlow.Builder builderForValue) {
      if (implicitBuilder_ == null) {
        flow_ = builderForValue.build();
        onChanged();
      } else {
        implicitBuilder_.setMessage(builderForValue.build());
      }
      flowCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     */
    public Builder mergeImplicit(com.google.a2a.v1.ImplicitOAuthFlow value) {
      if (implicitBuilder_ == null) {
        if (flowCase_ == 3 &&
            flow_ != com.google.a2a.v1.ImplicitOAuthFlow.getDefaultInstance()) {
          flow_ = com.google.a2a.v1.ImplicitOAuthFlow.newBuilder((com.google.a2a.v1.ImplicitOAuthFlow) flow_)
              .mergeFrom(value).buildPartial();
        } else {
          flow_ = value;
        }
        onChanged();
      } else {
        if (flowCase_ == 3) {
          implicitBuilder_.mergeFrom(value);
        } else {
          implicitBuilder_.setMessage(value);
        }
      }
      flowCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     */
    public Builder clearImplicit() {
      if (implicitBuilder_ == null) {
        if (flowCase_ == 3) {
          flowCase_ = 0;
          flow_ = null;
          onChanged();
        }
      } else {
        if (flowCase_ == 3) {
          flowCase_ = 0;
          flow_ = null;
        }
        implicitBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     */
    public com.google.a2a.v1.ImplicitOAuthFlow.Builder getImplicitBuilder() {
      return internalGetImplicitFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     */
    @java.lang.Override
    public com.google.a2a.v1.ImplicitOAuthFlowOrBuilder getImplicitOrBuilder() {
      if ((flowCase_ == 3) && (implicitBuilder_ != null)) {
        return implicitBuilder_.getMessageOrBuilder();
      } else {
        if (flowCase_ == 3) {
          return (com.google.a2a.v1.ImplicitOAuthFlow) flow_;
        }
        return com.google.a2a.v1.ImplicitOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.ImplicitOAuthFlow, com.google.a2a.v1.ImplicitOAuthFlow.Builder, com.google.a2a.v1.ImplicitOAuthFlowOrBuilder> 
        internalGetImplicitFieldBuilder() {
      if (implicitBuilder_ == null) {
        if (!(flowCase_ == 3)) {
          flow_ = com.google.a2a.v1.ImplicitOAuthFlow.getDefaultInstance();
        }
        implicitBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.ImplicitOAuthFlow, com.google.a2a.v1.ImplicitOAuthFlow.Builder, com.google.a2a.v1.ImplicitOAuthFlowOrBuilder>(
                (com.google.a2a.v1.ImplicitOAuthFlow) flow_,
                getParentForChildren(),
                isClean());
        flow_ = null;
      }
      flowCase_ = 3;
      onChanged();
      return implicitBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.PasswordOAuthFlow, com.google.a2a.v1.PasswordOAuthFlow.Builder, com.google.a2a.v1.PasswordOAuthFlowOrBuilder> passwordBuilder_;
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     * @return Whether the password field is set.
     */
    @java.lang.Override
    public boolean hasPassword() {
      return flowCase_ == 4;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     * @return The password.
     */
    @java.lang.Override
    public com.google.a2a.v1.PasswordOAuthFlow getPassword() {
      if (passwordBuilder_ == null) {
        if (flowCase_ == 4) {
          return (com.google.a2a.v1.PasswordOAuthFlow) flow_;
        }
        return com.google.a2a.v1.PasswordOAuthFlow.getDefaultInstance();
      } else {
        if (flowCase_ == 4) {
          return passwordBuilder_.getMessage();
        }
        return com.google.a2a.v1.PasswordOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     */
    public Builder setPassword(com.google.a2a.v1.PasswordOAuthFlow value) {
      if (passwordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flow_ = value;
        onChanged();
      } else {
        passwordBuilder_.setMessage(value);
      }
      flowCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     */
    public Builder setPassword(
        com.google.a2a.v1.PasswordOAuthFlow.Builder builderForValue) {
      if (passwordBuilder_ == null) {
        flow_ = builderForValue.build();
        onChanged();
      } else {
        passwordBuilder_.setMessage(builderForValue.build());
      }
      flowCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     */
    public Builder mergePassword(com.google.a2a.v1.PasswordOAuthFlow value) {
      if (passwordBuilder_ == null) {
        if (flowCase_ == 4 &&
            flow_ != com.google.a2a.v1.PasswordOAuthFlow.getDefaultInstance()) {
          flow_ = com.google.a2a.v1.PasswordOAuthFlow.newBuilder((com.google.a2a.v1.PasswordOAuthFlow) flow_)
              .mergeFrom(value).buildPartial();
        } else {
          flow_ = value;
        }
        onChanged();
      } else {
        if (flowCase_ == 4) {
          passwordBuilder_.mergeFrom(value);
        } else {
          passwordBuilder_.setMessage(value);
        }
      }
      flowCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     */
    public Builder clearPassword() {
      if (passwordBuilder_ == null) {
        if (flowCase_ == 4) {
          flowCase_ = 0;
          flow_ = null;
          onChanged();
        }
      } else {
        if (flowCase_ == 4) {
          flowCase_ = 0;
          flow_ = null;
        }
        passwordBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     */
    public com.google.a2a.v1.PasswordOAuthFlow.Builder getPasswordBuilder() {
      return internalGetPasswordFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     */
    @java.lang.Override
    public com.google.a2a.v1.PasswordOAuthFlowOrBuilder getPasswordOrBuilder() {
      if ((flowCase_ == 4) && (passwordBuilder_ != null)) {
        return passwordBuilder_.getMessageOrBuilder();
      } else {
        if (flowCase_ == 4) {
          return (com.google.a2a.v1.PasswordOAuthFlow) flow_;
        }
        return com.google.a2a.v1.PasswordOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.PasswordOAuthFlow, com.google.a2a.v1.PasswordOAuthFlow.Builder, com.google.a2a.v1.PasswordOAuthFlowOrBuilder> 
        internalGetPasswordFieldBuilder() {
      if (passwordBuilder_ == null) {
        if (!(flowCase_ == 4)) {
          flow_ = com.google.a2a.v1.PasswordOAuthFlow.getDefaultInstance();
        }
        passwordBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.PasswordOAuthFlow, com.google.a2a.v1.PasswordOAuthFlow.Builder, com.google.a2a.v1.PasswordOAuthFlowOrBuilder>(
                (com.google.a2a.v1.PasswordOAuthFlow) flow_,
                getParentForChildren(),
                isClean());
        flow_ = null;
      }
      flowCase_ = 4;
      onChanged();
      return passwordBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.OAuthFlows)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.OAuthFlows)
  private static final com.google.a2a.v1.OAuthFlows DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.a2a.v1.OAuthFlows();
  }

  public static com.google.a2a.v1.OAuthFlows getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OAuthFlows>
      PARSER = new com.google.protobuf.AbstractParser<OAuthFlows>() {
    @java.lang.Override
    public OAuthFlows parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OAuthFlows> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OAuthFlows> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.a2a.v1.OAuthFlows getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

