// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface SecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   * @return Whether the apiKeySecurityScheme field is set.
   */
  boolean hasApiKeySecurityScheme();
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   * @return The apiKeySecurityScheme.
   */
  com.google.a2a.v1.APIKeySecurityScheme getApiKeySecurityScheme();
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   */
  com.google.a2a.v1.APIKeySecuritySchemeOrBuilder getApiKeySecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   * @return Whether the httpAuthSecurityScheme field is set.
   */
  boolean hasHttpAuthSecurityScheme();
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   * @return The httpAuthSecurityScheme.
   */
  com.google.a2a.v1.HTTPAuthSecurityScheme getHttpAuthSecurityScheme();
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   */
  com.google.a2a.v1.HTTPAuthSecuritySchemeOrBuilder getHttpAuthSecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   * @return Whether the oauth2SecurityScheme field is set.
   */
  boolean hasOauth2SecurityScheme();
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   * @return The oauth2SecurityScheme.
   */
  com.google.a2a.v1.OAuth2SecurityScheme getOauth2SecurityScheme();
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   */
  com.google.a2a.v1.OAuth2SecuritySchemeOrBuilder getOauth2SecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   * @return Whether the openIdConnectSecurityScheme field is set.
   */
  boolean hasOpenIdConnectSecurityScheme();
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   * @return The openIdConnectSecurityScheme.
   */
  com.google.a2a.v1.OpenIdConnectSecurityScheme getOpenIdConnectSecurityScheme();
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   */
  com.google.a2a.v1.OpenIdConnectSecuritySchemeOrBuilder getOpenIdConnectSecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.MutualTlsSecurityScheme mtls_security_scheme = 5 [json_name = "mtlsSecurityScheme"];</code>
   * @return Whether the mtlsSecurityScheme field is set.
   */
  boolean hasMtlsSecurityScheme();
  /**
   * <code>.a2a.v1.MutualTlsSecurityScheme mtls_security_scheme = 5 [json_name = "mtlsSecurityScheme"];</code>
   * @return The mtlsSecurityScheme.
   */
  com.google.a2a.v1.MutualTlsSecurityScheme getMtlsSecurityScheme();
  /**
   * <code>.a2a.v1.MutualTlsSecurityScheme mtls_security_scheme = 5 [json_name = "mtlsSecurityScheme"];</code>
   */
  com.google.a2a.v1.MutualTlsSecuritySchemeOrBuilder getMtlsSecuritySchemeOrBuilder();

  com.google.a2a.v1.SecurityScheme.SchemeCase getSchemeCase();
}
