// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

/**
 * Protobuf type {@code a2a.v1.Security}
 */
@com.google.protobuf.Generated
public final class Security extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.Security)
    SecurityOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "Security");
  }
  // Use Security.newBuilder() to construct.
  private Security(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Security() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_Security_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetSchemes();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_Security_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.a2a.v1.Security.class, com.google.a2a.v1.Security.Builder.class);
  }

  public static final int SCHEMES_FIELD_NUMBER = 1;
  private static final class SchemesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.a2a.v1.StringList> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.a2a.v1.StringList>newDefaultInstance(
                com.google.a2a.v1.A2A.internal_static_a2a_v1_Security_SchemesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.google.a2a.v1.StringList.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.google.a2a.v1.StringList> schemes_;
  private com.google.protobuf.MapField<java.lang.String, com.google.a2a.v1.StringList>
  internalGetSchemes() {
    if (schemes_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SchemesDefaultEntryHolder.defaultEntry);
    }
    return schemes_;
  }
  public int getSchemesCount() {
    return internalGetSchemes().getMap().size();
  }
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
   */
  @java.lang.Override
  public boolean containsSchemes(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetSchemes().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSchemesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.a2a.v1.StringList> getSchemes() {
    return getSchemesMap();
  }
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.google.a2a.v1.StringList> getSchemesMap() {
    return internalGetSchemes().getMap();
  }
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.google.a2a.v1.StringList getSchemesOrDefault(
      java.lang.String key,
      /* nullable */
com.google.a2a.v1.StringList defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.a2a.v1.StringList> map =
        internalGetSchemes().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.StringList getSchemesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.a2a.v1.StringList> map =
        internalGetSchemes().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetSchemes(),
        SchemesDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.google.a2a.v1.StringList> entry
         : internalGetSchemes().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.a2a.v1.StringList>
      schemes__ = SchemesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, schemes__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.a2a.v1.Security)) {
      return super.equals(obj);
    }
    com.google.a2a.v1.Security other = (com.google.a2a.v1.Security) obj;

    if (!internalGetSchemes().equals(
        other.internalGetSchemes())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetSchemes().getMap().isEmpty()) {
      hash = (37 * hash) + SCHEMES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSchemes().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.a2a.v1.Security parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.Security parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.Security parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.Security parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.Security parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.Security parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.Security parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.Security parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.a2a.v1.Security parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.a2a.v1.Security parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.a2a.v1.Security parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.Security parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.a2a.v1.Security prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code a2a.v1.Security}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.Security)
      com.google.a2a.v1.SecurityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_Security_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetSchemes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableSchemes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_Security_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.a2a.v1.Security.class, com.google.a2a.v1.Security.Builder.class);
    }

    // Construct using com.google.a2a.v1.Security.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableSchemes().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_Security_descriptor;
    }

    @java.lang.Override
    public com.google.a2a.v1.Security getDefaultInstanceForType() {
      return com.google.a2a.v1.Security.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.a2a.v1.Security build() {
      com.google.a2a.v1.Security result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.a2a.v1.Security buildPartial() {
      com.google.a2a.v1.Security result = new com.google.a2a.v1.Security(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.a2a.v1.Security result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.schemes_ = internalGetSchemes().build(SchemesDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.a2a.v1.Security) {
        return mergeFrom((com.google.a2a.v1.Security)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.a2a.v1.Security other) {
      if (other == com.google.a2a.v1.Security.getDefaultInstance()) return this;
      internalGetMutableSchemes().mergeFrom(
          other.internalGetSchemes());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, com.google.a2a.v1.StringList>
              schemes__ = input.readMessage(
                  SchemesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableSchemes().ensureBuilderMap().put(
                  schemes__.getKey(), schemes__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class SchemesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.google.a2a.v1.StringListOrBuilder, com.google.a2a.v1.StringList> {
      @java.lang.Override
      public com.google.a2a.v1.StringList build(com.google.a2a.v1.StringListOrBuilder val) {
        if (val instanceof com.google.a2a.v1.StringList) { return (com.google.a2a.v1.StringList) val; }
        return ((com.google.a2a.v1.StringList.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.google.a2a.v1.StringList> defaultEntry() {
        return SchemesDefaultEntryHolder.defaultEntry;
      }
    };
    private static final SchemesConverter schemesConverter = new SchemesConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.google.a2a.v1.StringListOrBuilder, com.google.a2a.v1.StringList, com.google.a2a.v1.StringList.Builder> schemes_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.a2a.v1.StringListOrBuilder, com.google.a2a.v1.StringList, com.google.a2a.v1.StringList.Builder>
        internalGetSchemes() {
      if (schemes_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(schemesConverter);
      }
      return schemes_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.a2a.v1.StringListOrBuilder, com.google.a2a.v1.StringList, com.google.a2a.v1.StringList.Builder>
        internalGetMutableSchemes() {
      if (schemes_ == null) {
        schemes_ = new com.google.protobuf.MapFieldBuilder<>(schemesConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return schemes_;
    }
    public int getSchemesCount() {
      return internalGetSchemes().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
     */
    @java.lang.Override
    public boolean containsSchemes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSchemes().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getSchemesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.a2a.v1.StringList> getSchemes() {
      return getSchemesMap();
    }
    /**
     * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.a2a.v1.StringList> getSchemesMap() {
      return internalGetSchemes().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.a2a.v1.StringList getSchemesOrDefault(
        java.lang.String key,
        /* nullable */
com.google.a2a.v1.StringList defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.a2a.v1.StringListOrBuilder> map = internalGetMutableSchemes().ensureBuilderMap();
      return map.containsKey(key) ? schemesConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
     */
    @java.lang.Override
    public com.google.a2a.v1.StringList getSchemesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.a2a.v1.StringListOrBuilder> map = internalGetMutableSchemes().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return schemesConverter.build(map.get(key));
    }
    public Builder clearSchemes() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableSchemes().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
     */
    public Builder removeSchemes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableSchemes().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.a2a.v1.StringList>
        getMutableSchemes() {
      bitField0_ |= 0x00000001;
      return internalGetMutableSchemes().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
     */
    public Builder putSchemes(
        java.lang.String key,
        com.google.a2a.v1.StringList value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableSchemes().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
     */
    public Builder putAllSchemes(
        java.util.Map<java.lang.String, com.google.a2a.v1.StringList> values) {
      for (java.util.Map.Entry<java.lang.String, com.google.a2a.v1.StringList> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableSchemes().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1 [json_name = "schemes"];</code>
     */
    public com.google.a2a.v1.StringList.Builder putSchemesBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.google.a2a.v1.StringListOrBuilder> builderMap = internalGetMutableSchemes().ensureBuilderMap();
      com.google.a2a.v1.StringListOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.google.a2a.v1.StringList.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.google.a2a.v1.StringList) {
        entry = ((com.google.a2a.v1.StringList) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.google.a2a.v1.StringList.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.Security)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.Security)
  private static final com.google.a2a.v1.Security DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.a2a.v1.Security();
  }

  public static com.google.a2a.v1.Security getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Security>
      PARSER = new com.google.protobuf.AbstractParser<Security>() {
    @java.lang.Override
    public Security parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Security> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Security> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.a2a.v1.Security getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

