// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface SendMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SendMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return The task.
   */
  com.google.a2a.v1.Task getTask();
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   */
  com.google.a2a.v1.TaskOrBuilder getTaskOrBuilder();

  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return The msg.
   */
  com.google.a2a.v1.Message getMsg();
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   */
  com.google.a2a.v1.MessageOrBuilder getMsgOrBuilder();

  com.google.a2a.v1.SendMessageResponse.PayloadCase getPayloadCase();
}
