// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

/**
 * <pre>
 * &#47;///// Response Messages ///////////
 * --8&lt;-- [start:SendMessageSuccessResponse]
 * </pre>
 *
 * Protobuf type {@code a2a.v1.SendMessageResponse}
 */
@com.google.protobuf.Generated
public final class SendMessageResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.SendMessageResponse)
    SendMessageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "SendMessageResponse");
  }
  // Use SendMessageResponse.newBuilder() to construct.
  private SendMessageResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SendMessageResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.a2a.v1.SendMessageResponse.class, com.google.a2a.v1.SendMessageResponse.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TASK(1),
    MSG(2),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1: return TASK;
        case 2: return MSG;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TASK_FIELD_NUMBER = 1;
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return Whether the task field is set.
   */
  @java.lang.Override
  public boolean hasTask() {
    return payloadCase_ == 1;
  }
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return The task.
   */
  @java.lang.Override
  public com.google.a2a.v1.Task getTask() {
    if (payloadCase_ == 1) {
       return (com.google.a2a.v1.Task) payload_;
    }
    return com.google.a2a.v1.Task.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.TaskOrBuilder getTaskOrBuilder() {
    if (payloadCase_ == 1) {
       return (com.google.a2a.v1.Task) payload_;
    }
    return com.google.a2a.v1.Task.getDefaultInstance();
  }

  public static final int MSG_FIELD_NUMBER = 2;
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return Whether the msg field is set.
   */
  @java.lang.Override
  public boolean hasMsg() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return The msg.
   */
  @java.lang.Override
  public com.google.a2a.v1.Message getMsg() {
    if (payloadCase_ == 2) {
       return (com.google.a2a.v1.Message) payload_;
    }
    return com.google.a2a.v1.Message.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.MessageOrBuilder getMsgOrBuilder() {
    if (payloadCase_ == 2) {
       return (com.google.a2a.v1.Message) payload_;
    }
    return com.google.a2a.v1.Message.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (com.google.a2a.v1.Task) payload_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (com.google.a2a.v1.Message) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.google.a2a.v1.Task) payload_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.google.a2a.v1.Message) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.a2a.v1.SendMessageResponse)) {
      return super.equals(obj);
    }
    com.google.a2a.v1.SendMessageResponse other = (com.google.a2a.v1.SendMessageResponse) obj;

    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1:
        if (!getTask()
            .equals(other.getTask())) return false;
        break;
      case 2:
        if (!getMsg()
            .equals(other.getMsg())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + TASK_FIELD_NUMBER;
        hash = (53 * hash) + getTask().hashCode();
        break;
      case 2:
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.a2a.v1.SendMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.a2a.v1.SendMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.a2a.v1.SendMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.SendMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.a2a.v1.SendMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * &#47;///// Response Messages ///////////
   * --8&lt;-- [start:SendMessageSuccessResponse]
   * </pre>
   *
   * Protobuf type {@code a2a.v1.SendMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.SendMessageResponse)
      com.google.a2a.v1.SendMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.a2a.v1.SendMessageResponse.class, com.google.a2a.v1.SendMessageResponse.Builder.class);
    }

    // Construct using com.google.a2a.v1.SendMessageResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (taskBuilder_ != null) {
        taskBuilder_.clear();
      }
      if (msgBuilder_ != null) {
        msgBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageResponse_descriptor;
    }

    @java.lang.Override
    public com.google.a2a.v1.SendMessageResponse getDefaultInstanceForType() {
      return com.google.a2a.v1.SendMessageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.a2a.v1.SendMessageResponse build() {
      com.google.a2a.v1.SendMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.a2a.v1.SendMessageResponse buildPartial() {
      com.google.a2a.v1.SendMessageResponse result = new com.google.a2a.v1.SendMessageResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.a2a.v1.SendMessageResponse result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.google.a2a.v1.SendMessageResponse result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1 &&
          taskBuilder_ != null) {
        result.payload_ = taskBuilder_.build();
      }
      if (payloadCase_ == 2 &&
          msgBuilder_ != null) {
        result.payload_ = msgBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.a2a.v1.SendMessageResponse) {
        return mergeFrom((com.google.a2a.v1.SendMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.a2a.v1.SendMessageResponse other) {
      if (other == com.google.a2a.v1.SendMessageResponse.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case TASK: {
          mergeTask(other.getTask());
          break;
        }
        case MSG: {
          mergeMsg(other.getMsg());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetTaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetMsgFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.Task, com.google.a2a.v1.Task.Builder, com.google.a2a.v1.TaskOrBuilder> taskBuilder_;
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     * @return Whether the task field is set.
     */
    @java.lang.Override
    public boolean hasTask() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     * @return The task.
     */
    @java.lang.Override
    public com.google.a2a.v1.Task getTask() {
      if (taskBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (com.google.a2a.v1.Task) payload_;
        }
        return com.google.a2a.v1.Task.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return taskBuilder_.getMessage();
        }
        return com.google.a2a.v1.Task.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public Builder setTask(com.google.a2a.v1.Task value) {
      if (taskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        taskBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public Builder setTask(
        com.google.a2a.v1.Task.Builder builderForValue) {
      if (taskBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        taskBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public Builder mergeTask(com.google.a2a.v1.Task value) {
      if (taskBuilder_ == null) {
        if (payloadCase_ == 1 &&
            payload_ != com.google.a2a.v1.Task.getDefaultInstance()) {
          payload_ = com.google.a2a.v1.Task.newBuilder((com.google.a2a.v1.Task) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          taskBuilder_.mergeFrom(value);
        } else {
          taskBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public Builder clearTask() {
      if (taskBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        taskBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public com.google.a2a.v1.Task.Builder getTaskBuilder() {
      return internalGetTaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    @java.lang.Override
    public com.google.a2a.v1.TaskOrBuilder getTaskOrBuilder() {
      if ((payloadCase_ == 1) && (taskBuilder_ != null)) {
        return taskBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (com.google.a2a.v1.Task) payload_;
        }
        return com.google.a2a.v1.Task.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.Task, com.google.a2a.v1.Task.Builder, com.google.a2a.v1.TaskOrBuilder> 
        internalGetTaskFieldBuilder() {
      if (taskBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = com.google.a2a.v1.Task.getDefaultInstance();
        }
        taskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.Task, com.google.a2a.v1.Task.Builder, com.google.a2a.v1.TaskOrBuilder>(
                (com.google.a2a.v1.Task) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();
      return taskBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder> msgBuilder_;
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     * @return The msg.
     */
    @java.lang.Override
    public com.google.a2a.v1.Message getMsg() {
      if (msgBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (com.google.a2a.v1.Message) payload_;
        }
        return com.google.a2a.v1.Message.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return msgBuilder_.getMessage();
        }
        return com.google.a2a.v1.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public Builder setMsg(com.google.a2a.v1.Message value) {
      if (msgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        msgBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public Builder setMsg(
        com.google.a2a.v1.Message.Builder builderForValue) {
      if (msgBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        msgBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public Builder mergeMsg(com.google.a2a.v1.Message value) {
      if (msgBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != com.google.a2a.v1.Message.getDefaultInstance()) {
          payload_ = com.google.a2a.v1.Message.newBuilder((com.google.a2a.v1.Message) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          msgBuilder_.mergeFrom(value);
        } else {
          msgBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public Builder clearMsg() {
      if (msgBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        msgBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public com.google.a2a.v1.Message.Builder getMsgBuilder() {
      return internalGetMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    @java.lang.Override
    public com.google.a2a.v1.MessageOrBuilder getMsgOrBuilder() {
      if ((payloadCase_ == 2) && (msgBuilder_ != null)) {
        return msgBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (com.google.a2a.v1.Message) payload_;
        }
        return com.google.a2a.v1.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder> 
        internalGetMsgFieldBuilder() {
      if (msgBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = com.google.a2a.v1.Message.getDefaultInstance();
        }
        msgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder>(
                (com.google.a2a.v1.Message) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return msgBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.SendMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.SendMessageResponse)
  private static final com.google.a2a.v1.SendMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.a2a.v1.SendMessageResponse();
  }

  public static com.google.a2a.v1.SendMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<SendMessageResponse>() {
    @java.lang.Override
    public SendMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SendMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendMessageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.a2a.v1.SendMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

