// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

/**
 * <pre>
 * &#47;////////// Request Messages ///////////
 * --8&lt;-- [start:MessageSendParams]
 * </pre>
 *
 * Protobuf type {@code a2a.v1.SendMessageRequest}
 */
@com.google.protobuf.Generated
public final class SendMessageRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.SendMessageRequest)
    SendMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "SendMessageRequest");
  }
  // Use SendMessageRequest.newBuilder() to construct.
  private SendMessageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SendMessageRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.a2a.v1.SendMessageRequest.class, com.google.a2a.v1.SendMessageRequest.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_FIELD_NUMBER = 1;
  private com.google.a2a.v1.Message request_;
  /**
   * <pre>
   * The message to send to the agent.
   * </pre>
   *
   * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the request field is set.
   */
  @java.lang.Override
  public boolean hasRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The message to send to the agent.
   * </pre>
   *
   * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The request.
   */
  @java.lang.Override
  public com.google.a2a.v1.Message getRequest() {
    return request_ == null ? com.google.a2a.v1.Message.getDefaultInstance() : request_;
  }
  /**
   * <pre>
   * The message to send to the agent.
   * </pre>
   *
   * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.MessageOrBuilder getRequestOrBuilder() {
    return request_ == null ? com.google.a2a.v1.Message.getDefaultInstance() : request_;
  }

  public static final int CONFIGURATION_FIELD_NUMBER = 2;
  private com.google.a2a.v1.SendMessageConfiguration configuration_;
  /**
   * <pre>
   * Configuration for the send request.
   * </pre>
   *
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
   * @return Whether the configuration field is set.
   */
  @java.lang.Override
  public boolean hasConfiguration() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Configuration for the send request.
   * </pre>
   *
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
   * @return The configuration.
   */
  @java.lang.Override
  public com.google.a2a.v1.SendMessageConfiguration getConfiguration() {
    return configuration_ == null ? com.google.a2a.v1.SendMessageConfiguration.getDefaultInstance() : configuration_;
  }
  /**
   * <pre>
   * Configuration for the send request.
   * </pre>
   *
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.SendMessageConfigurationOrBuilder getConfigurationOrBuilder() {
    return configuration_ == null ? com.google.a2a.v1.SendMessageConfiguration.getDefaultInstance() : configuration_;
  }

  public static final int METADATA_FIELD_NUMBER = 3;
  private com.google.protobuf.Struct metadata_;
  /**
   * <pre>
   * Optional metadata for the request.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Optional metadata for the request.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMetadata() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * Optional metadata for the request.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRequest());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getConfiguration());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getMetadata());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRequest());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getConfiguration());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMetadata());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.a2a.v1.SendMessageRequest)) {
      return super.equals(obj);
    }
    com.google.a2a.v1.SendMessageRequest other = (com.google.a2a.v1.SendMessageRequest) obj;

    if (hasRequest() != other.hasRequest()) return false;
    if (hasRequest()) {
      if (!getRequest()
          .equals(other.getRequest())) return false;
    }
    if (hasConfiguration() != other.hasConfiguration()) return false;
    if (hasConfiguration()) {
      if (!getConfiguration()
          .equals(other.getConfiguration())) return false;
    }
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequest()) {
      hash = (37 * hash) + REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getRequest().hashCode();
    }
    if (hasConfiguration()) {
      hash = (37 * hash) + CONFIGURATION_FIELD_NUMBER;
      hash = (53 * hash) + getConfiguration().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.a2a.v1.SendMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.a2a.v1.SendMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.a2a.v1.SendMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.SendMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.a2a.v1.SendMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * &#47;////////// Request Messages ///////////
   * --8&lt;-- [start:MessageSendParams]
   * </pre>
   *
   * Protobuf type {@code a2a.v1.SendMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.SendMessageRequest)
      com.google.a2a.v1.SendMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.a2a.v1.SendMessageRequest.class, com.google.a2a.v1.SendMessageRequest.Builder.class);
    }

    // Construct using com.google.a2a.v1.SendMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRequestFieldBuilder();
        internalGetConfigurationFieldBuilder();
        internalGetMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      request_ = null;
      if (requestBuilder_ != null) {
        requestBuilder_.dispose();
        requestBuilder_ = null;
      }
      configuration_ = null;
      if (configurationBuilder_ != null) {
        configurationBuilder_.dispose();
        configurationBuilder_ = null;
      }
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_SendMessageRequest_descriptor;
    }

    @java.lang.Override
    public com.google.a2a.v1.SendMessageRequest getDefaultInstanceForType() {
      return com.google.a2a.v1.SendMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.a2a.v1.SendMessageRequest build() {
      com.google.a2a.v1.SendMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.a2a.v1.SendMessageRequest buildPartial() {
      com.google.a2a.v1.SendMessageRequest result = new com.google.a2a.v1.SendMessageRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.a2a.v1.SendMessageRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.request_ = requestBuilder_ == null
            ? request_
            : requestBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.configuration_ = configurationBuilder_ == null
            ? configuration_
            : configurationBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.a2a.v1.SendMessageRequest) {
        return mergeFrom((com.google.a2a.v1.SendMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.a2a.v1.SendMessageRequest other) {
      if (other == com.google.a2a.v1.SendMessageRequest.getDefaultInstance()) return this;
      if (other.hasRequest()) {
        mergeRequest(other.getRequest());
      }
      if (other.hasConfiguration()) {
        mergeConfiguration(other.getConfiguration());
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetConfigurationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.a2a.v1.Message request_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder> requestBuilder_;
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The request.
     */
    public com.google.a2a.v1.Message getRequest() {
      if (requestBuilder_ == null) {
        return request_ == null ? com.google.a2a.v1.Message.getDefaultInstance() : request_;
      } else {
        return requestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setRequest(com.google.a2a.v1.Message value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
      } else {
        requestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setRequest(
        com.google.a2a.v1.Message.Builder builderForValue) {
      if (requestBuilder_ == null) {
        request_ = builderForValue.build();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeRequest(com.google.a2a.v1.Message value) {
      if (requestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          request_ != null &&
          request_ != com.google.a2a.v1.Message.getDefaultInstance()) {
          getRequestBuilder().mergeFrom(value);
        } else {
          request_ = value;
        }
      } else {
        requestBuilder_.mergeFrom(value);
      }
      if (request_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearRequest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      request_ = null;
      if (requestBuilder_ != null) {
        requestBuilder_.dispose();
        requestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.a2a.v1.Message.Builder getRequestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public com.google.a2a.v1.MessageOrBuilder getRequestOrBuilder() {
      if (requestBuilder_ != null) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        return request_ == null ?
            com.google.a2a.v1.Message.getDefaultInstance() : request_;
      }
    }
    /**
     * <pre>
     * The message to send to the agent.
     * </pre>
     *
     * <code>.a2a.v1.Message request = 1 [json_name = "message", (.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder> 
        internalGetRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder>(
                getRequest(),
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      return requestBuilder_;
    }

    private com.google.a2a.v1.SendMessageConfiguration configuration_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.SendMessageConfiguration, com.google.a2a.v1.SendMessageConfiguration.Builder, com.google.a2a.v1.SendMessageConfigurationOrBuilder> configurationBuilder_;
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     * @return Whether the configuration field is set.
     */
    public boolean hasConfiguration() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     * @return The configuration.
     */
    public com.google.a2a.v1.SendMessageConfiguration getConfiguration() {
      if (configurationBuilder_ == null) {
        return configuration_ == null ? com.google.a2a.v1.SendMessageConfiguration.getDefaultInstance() : configuration_;
      } else {
        return configurationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     */
    public Builder setConfiguration(com.google.a2a.v1.SendMessageConfiguration value) {
      if (configurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        configuration_ = value;
      } else {
        configurationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     */
    public Builder setConfiguration(
        com.google.a2a.v1.SendMessageConfiguration.Builder builderForValue) {
      if (configurationBuilder_ == null) {
        configuration_ = builderForValue.build();
      } else {
        configurationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     */
    public Builder mergeConfiguration(com.google.a2a.v1.SendMessageConfiguration value) {
      if (configurationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          configuration_ != null &&
          configuration_ != com.google.a2a.v1.SendMessageConfiguration.getDefaultInstance()) {
          getConfigurationBuilder().mergeFrom(value);
        } else {
          configuration_ = value;
        }
      } else {
        configurationBuilder_.mergeFrom(value);
      }
      if (configuration_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     */
    public Builder clearConfiguration() {
      bitField0_ = (bitField0_ & ~0x00000002);
      configuration_ = null;
      if (configurationBuilder_ != null) {
        configurationBuilder_.dispose();
        configurationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     */
    public com.google.a2a.v1.SendMessageConfiguration.Builder getConfigurationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetConfigurationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     */
    public com.google.a2a.v1.SendMessageConfigurationOrBuilder getConfigurationOrBuilder() {
      if (configurationBuilder_ != null) {
        return configurationBuilder_.getMessageOrBuilder();
      } else {
        return configuration_ == null ?
            com.google.a2a.v1.SendMessageConfiguration.getDefaultInstance() : configuration_;
      }
    }
    /**
     * <pre>
     * Configuration for the send request.
     * </pre>
     *
     * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.SendMessageConfiguration, com.google.a2a.v1.SendMessageConfiguration.Builder, com.google.a2a.v1.SendMessageConfigurationOrBuilder> 
        internalGetConfigurationFieldBuilder() {
      if (configurationBuilder_ == null) {
        configurationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.SendMessageConfiguration, com.google.a2a.v1.SendMessageConfiguration.Builder, com.google.a2a.v1.SendMessageConfigurationOrBuilder>(
                getConfiguration(),
                getParentForChildren(),
                isClean());
        configuration_ = null;
      }
      return configurationBuilder_;
    }

    private com.google.protobuf.Struct metadata_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     * @return The metadata.
     */
    public com.google.protobuf.Struct getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     */
    public Builder setMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     */
    public Builder setMetadata(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     */
    public Builder mergeMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          metadata_ != null &&
          metadata_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000004);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     */
    public com.google.protobuf.Struct.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     */
    public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * Optional metadata for the request.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        internalGetMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.SendMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.SendMessageRequest)
  private static final com.google.a2a.v1.SendMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.a2a.v1.SendMessageRequest();
  }

  public static com.google.a2a.v1.SendMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendMessageRequest>() {
    @java.lang.Override
    public SendMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SendMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.a2a.v1.SendMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

