// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return The task.
   */
  com.google.a2a.v1.Task getTask();
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   */
  com.google.a2a.v1.TaskOrBuilder getTaskOrBuilder();

  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return The msg.
   */
  com.google.a2a.v1.Message getMsg();
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   */
  com.google.a2a.v1.MessageOrBuilder getMsgOrBuilder();

  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
   * @return Whether the statusUpdate field is set.
   */
  boolean hasStatusUpdate();
  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
   * @return The statusUpdate.
   */
  com.google.a2a.v1.TaskStatusUpdateEvent getStatusUpdate();
  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
   */
  com.google.a2a.v1.TaskStatusUpdateEventOrBuilder getStatusUpdateOrBuilder();

  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
   * @return Whether the artifactUpdate field is set.
   */
  boolean hasArtifactUpdate();
  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
   * @return The artifactUpdate.
   */
  com.google.a2a.v1.TaskArtifactUpdateEvent getArtifactUpdate();
  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
   */
  com.google.a2a.v1.TaskArtifactUpdateEventOrBuilder getArtifactUpdateOrBuilder();

  com.google.a2a.v1.StreamResponse.PayloadCase getPayloadCase();
}
