// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface StringListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.StringList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string list = 1 [json_name = "list"];</code>
   * @return A list containing the list.
   */
  java.util.List<java.lang.String>
      getListList();
  /**
   * <code>repeated string list = 1 [json_name = "list"];</code>
   * @return The count of list.
   */
  int getListCount();
  /**
   * <code>repeated string list = 1 [json_name = "list"];</code>
   * @param index The index of the element to return.
   * @return The list at the given index.
   */
  java.lang.String getList(int index);
  /**
   * <code>repeated string list = 1 [json_name = "list"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the list at the given index.
   */
  com.google.protobuf.ByteString
      getListBytes(int index);
}
