// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface TaskStatusUpdateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.TaskStatusUpdateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the task that is changed
   * </pre>
   *
   * <code>string task_id = 1 [json_name = "taskId"];</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * The id of the task that is changed
   * </pre>
   *
   * <code>string task_id = 1 [json_name = "taskId"];</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * The id of the context that the task belongs to
   * </pre>
   *
   * <code>string context_id = 2 [json_name = "contextId"];</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * The id of the context that the task belongs to
   * </pre>
   *
   * <code>string context_id = 2 [json_name = "contextId"];</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * The new status of the task.
   * </pre>
   *
   * <code>.a2a.v1.TaskStatus status = 3 [json_name = "status"];</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * The new status of the task.
   * </pre>
   *
   * <code>.a2a.v1.TaskStatus status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  com.google.a2a.v1.TaskStatus getStatus();
  /**
   * <pre>
   * The new status of the task.
   * </pre>
   *
   * <code>.a2a.v1.TaskStatus status = 3 [json_name = "status"];</code>
   */
  com.google.a2a.v1.TaskStatusOrBuilder getStatusOrBuilder();

  /**
   * <pre>
   * Whether this is the last status update expected for this task.
   * </pre>
   *
   * <code>bool final = 4 [json_name = "final"];</code>
   * @return The final.
   */
  boolean getFinal();

  /**
   * <pre>
   * Optional metadata to associate with the task update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 5 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Optional metadata to associate with the task update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 5 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * Optional metadata to associate with the task update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 5 [json_name = "metadata"];</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
