// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface TaskStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.TaskStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The current state of this task
   * </pre>
   *
   * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * The current state of this task
   * </pre>
   *
   * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
   * @return The state.
   */
  com.google.a2a.v1.TaskState getState();

  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
   * @return Whether the update field is set.
   */
  boolean hasUpdate();
  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
   * @return The update.
   */
  com.google.a2a.v1.Message getUpdate();
  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
   */
  com.google.a2a.v1.MessageOrBuilder getUpdateOrBuilder();

  /**
   * <pre>
   * Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
