// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface TaskArtifactUpdateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.TaskArtifactUpdateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the task for this artifact
   * </pre>
   *
   * <code>string task_id = 1 [json_name = "taskId"];</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * The id of the task for this artifact
   * </pre>
   *
   * <code>string task_id = 1 [json_name = "taskId"];</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * The id of the context that this task belongs too
   * </pre>
   *
   * <code>string context_id = 2 [json_name = "contextId"];</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * The id of the context that this task belongs too
   * </pre>
   *
   * <code>string context_id = 2 [json_name = "contextId"];</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * The artifact itself
   * </pre>
   *
   * <code>.a2a.v1.Artifact artifact = 3 [json_name = "artifact"];</code>
   * @return Whether the artifact field is set.
   */
  boolean hasArtifact();
  /**
   * <pre>
   * The artifact itself
   * </pre>
   *
   * <code>.a2a.v1.Artifact artifact = 3 [json_name = "artifact"];</code>
   * @return The artifact.
   */
  com.google.a2a.v1.Artifact getArtifact();
  /**
   * <pre>
   * The artifact itself
   * </pre>
   *
   * <code>.a2a.v1.Artifact artifact = 3 [json_name = "artifact"];</code>
   */
  com.google.a2a.v1.ArtifactOrBuilder getArtifactOrBuilder();

  /**
   * <pre>
   * Whether this should be appended to a prior one produced
   * </pre>
   *
   * <code>bool append = 4 [json_name = "append"];</code>
   * @return The append.
   */
  boolean getAppend();

  /**
   * <pre>
   * Whether this represents the last part of an artifact
   * </pre>
   *
   * <code>bool last_chunk = 5 [json_name = "lastChunk"];</code>
   * @return The lastChunk.
   */
  boolean getLastChunk();

  /**
   * <pre>
   * Optional metadata associated with the artifact update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Optional metadata associated with the artifact update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * Optional metadata associated with the artifact update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
