// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

@com.google.protobuf.Generated
public interface TaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.Task)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages). Created by the A2A server.
   * </pre>
   *
   * <code>string context_id = 2 [json_name = "contextId"];</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages). Created by the A2A server.
   * </pre>
   *
   * <code>string context_id = 2 [json_name = "contextId"];</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * The current status of a Task, including state and a message.
   * </pre>
   *
   * <code>.a2a.v1.TaskStatus status = 3 [json_name = "status"];</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * The current status of a Task, including state and a message.
   * </pre>
   *
   * <code>.a2a.v1.TaskStatus status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  com.google.a2a.v1.TaskStatus getStatus();
  /**
   * <pre>
   * The current status of a Task, including state and a message.
   * </pre>
   *
   * <code>.a2a.v1.TaskStatus status = 3 [json_name = "status"];</code>
   */
  com.google.a2a.v1.TaskStatusOrBuilder getStatusOrBuilder();

  /**
   * <pre>
   * A set of output artifacts for a Task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Artifact artifacts = 4 [json_name = "artifacts"];</code>
   */
  java.util.List<com.google.a2a.v1.Artifact> 
      getArtifactsList();
  /**
   * <pre>
   * A set of output artifacts for a Task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Artifact artifacts = 4 [json_name = "artifacts"];</code>
   */
  com.google.a2a.v1.Artifact getArtifacts(int index);
  /**
   * <pre>
   * A set of output artifacts for a Task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Artifact artifacts = 4 [json_name = "artifacts"];</code>
   */
  int getArtifactsCount();
  /**
   * <pre>
   * A set of output artifacts for a Task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Artifact artifacts = 4 [json_name = "artifacts"];</code>
   */
  java.util.List<? extends com.google.a2a.v1.ArtifactOrBuilder> 
      getArtifactsOrBuilderList();
  /**
   * <pre>
   * A set of output artifacts for a Task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Artifact artifacts = 4 [json_name = "artifacts"];</code>
   */
  com.google.a2a.v1.ArtifactOrBuilder getArtifactsOrBuilder(
      int index);

  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Message history = 5 [json_name = "history"];</code>
   */
  java.util.List<com.google.a2a.v1.Message> 
      getHistoryList();
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Message history = 5 [json_name = "history"];</code>
   */
  com.google.a2a.v1.Message getHistory(int index);
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Message history = 5 [json_name = "history"];</code>
   */
  int getHistoryCount();
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Message history = 5 [json_name = "history"];</code>
   */
  java.util.List<? extends com.google.a2a.v1.MessageOrBuilder> 
      getHistoryOrBuilderList();
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a task.
   * </pre>
   *
   * <code>repeated .a2a.v1.Message history = 5 [json_name = "history"];</code>
   */
  com.google.a2a.v1.MessageOrBuilder getHistoryOrBuilder(
      int index);

  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6 [json_name = "metadata"];</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
