// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.5

package com.google.a2a.v1;

/**
 * <pre>
 * --8&lt;-- [start:TaskStatus]
 * A container for the status of a task
 * </pre>
 *
 * Protobuf type {@code a2a.v1.TaskStatus}
 */
@com.google.protobuf.Generated
public final class TaskStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.TaskStatus)
    TaskStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "TaskStatus");
  }
  // Use TaskStatus.newBuilder() to construct.
  private TaskStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TaskStatus() {
    state_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_TaskStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.a2a.v1.A2A.internal_static_a2a_v1_TaskStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.a2a.v1.TaskStatus.class, com.google.a2a.v1.TaskStatus.Builder.class);
  }

  private int bitField0_;
  public static final int STATE_FIELD_NUMBER = 1;
  private int state_ = 0;
  /**
   * <pre>
   * The current state of this task
   * </pre>
   *
   * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <pre>
   * The current state of this task
   * </pre>
   *
   * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
   * @return The state.
   */
  @java.lang.Override public com.google.a2a.v1.TaskState getState() {
    com.google.a2a.v1.TaskState result = com.google.a2a.v1.TaskState.forNumber(state_);
    return result == null ? com.google.a2a.v1.TaskState.UNRECOGNIZED : result;
  }

  public static final int UPDATE_FIELD_NUMBER = 2;
  private com.google.a2a.v1.Message update_;
  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
   * @return Whether the update field is set.
   */
  @java.lang.Override
  public boolean hasUpdate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
   * @return The update.
   */
  @java.lang.Override
  public com.google.a2a.v1.Message getUpdate() {
    return update_ == null ? com.google.a2a.v1.Message.getDefaultInstance() : update_;
  }
  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
   */
  @java.lang.Override
  public com.google.a2a.v1.MessageOrBuilder getUpdateOrBuilder() {
    return update_ == null ? com.google.a2a.v1.Message.getDefaultInstance() : update_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <pre>
   * Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <pre>
   * Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (state_ != com.google.a2a.v1.TaskState.TASK_STATE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, state_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getUpdate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getTimestamp());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (state_ != com.google.a2a.v1.TaskState.TASK_STATE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, state_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpdate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTimestamp());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.a2a.v1.TaskStatus)) {
      return super.equals(obj);
    }
    com.google.a2a.v1.TaskStatus other = (com.google.a2a.v1.TaskStatus) obj;

    if (state_ != other.state_) return false;
    if (hasUpdate() != other.hasUpdate()) return false;
    if (hasUpdate()) {
      if (!getUpdate()
          .equals(other.getUpdate())) return false;
    }
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    if (hasUpdate()) {
      hash = (37 * hash) + UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getUpdate().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.a2a.v1.TaskStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.a2a.v1.TaskStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.a2a.v1.TaskStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.a2a.v1.TaskStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.a2a.v1.TaskStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:TaskStatus]
   * A container for the status of a task
   * </pre>
   *
   * Protobuf type {@code a2a.v1.TaskStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.TaskStatus)
      com.google.a2a.v1.TaskStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_TaskStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_TaskStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.a2a.v1.TaskStatus.class, com.google.a2a.v1.TaskStatus.Builder.class);
    }

    // Construct using com.google.a2a.v1.TaskStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetUpdateFieldBuilder();
        internalGetTimestampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      state_ = 0;
      update_ = null;
      if (updateBuilder_ != null) {
        updateBuilder_.dispose();
        updateBuilder_ = null;
      }
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.a2a.v1.A2A.internal_static_a2a_v1_TaskStatus_descriptor;
    }

    @java.lang.Override
    public com.google.a2a.v1.TaskStatus getDefaultInstanceForType() {
      return com.google.a2a.v1.TaskStatus.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.a2a.v1.TaskStatus build() {
      com.google.a2a.v1.TaskStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.a2a.v1.TaskStatus buildPartial() {
      com.google.a2a.v1.TaskStatus result = new com.google.a2a.v1.TaskStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.a2a.v1.TaskStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.state_ = state_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.update_ = updateBuilder_ == null
            ? update_
            : updateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.a2a.v1.TaskStatus) {
        return mergeFrom((com.google.a2a.v1.TaskStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.a2a.v1.TaskStatus other) {
      if (other == com.google.a2a.v1.TaskStatus.getDefaultInstance()) return this;
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.hasUpdate()) {
        mergeUpdate(other.getUpdate());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              state_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetUpdateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int state_ = 0;
    /**
     * <pre>
     * The current state of this task
     * </pre>
     *
     * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * The current state of this task
     * </pre>
     *
     * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The current state of this task
     * </pre>
     *
     * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
     * @return The state.
     */
    @java.lang.Override
    public com.google.a2a.v1.TaskState getState() {
      com.google.a2a.v1.TaskState result = com.google.a2a.v1.TaskState.forNumber(state_);
      return result == null ? com.google.a2a.v1.TaskState.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The current state of this task
     * </pre>
     *
     * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.google.a2a.v1.TaskState value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The current state of this task
     * </pre>
     *
     * <code>.a2a.v1.TaskState state = 1 [json_name = "state"];</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000001);
      state_ = 0;
      onChanged();
      return this;
    }

    private com.google.a2a.v1.Message update_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder> updateBuilder_;
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     * @return Whether the update field is set.
     */
    public boolean hasUpdate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     * @return The update.
     */
    public com.google.a2a.v1.Message getUpdate() {
      if (updateBuilder_ == null) {
        return update_ == null ? com.google.a2a.v1.Message.getDefaultInstance() : update_;
      } else {
        return updateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     */
    public Builder setUpdate(com.google.a2a.v1.Message value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        update_ = value;
      } else {
        updateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     */
    public Builder setUpdate(
        com.google.a2a.v1.Message.Builder builderForValue) {
      if (updateBuilder_ == null) {
        update_ = builderForValue.build();
      } else {
        updateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     */
    public Builder mergeUpdate(com.google.a2a.v1.Message value) {
      if (updateBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          update_ != null &&
          update_ != com.google.a2a.v1.Message.getDefaultInstance()) {
          getUpdateBuilder().mergeFrom(value);
        } else {
          update_ = value;
        }
      } else {
        updateBuilder_.mergeFrom(value);
      }
      if (update_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     */
    public Builder clearUpdate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      update_ = null;
      if (updateBuilder_ != null) {
        updateBuilder_.dispose();
        updateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     */
    public com.google.a2a.v1.Message.Builder getUpdateBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetUpdateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     */
    public com.google.a2a.v1.MessageOrBuilder getUpdateOrBuilder() {
      if (updateBuilder_ != null) {
        return updateBuilder_.getMessageOrBuilder();
      } else {
        return update_ == null ?
            com.google.a2a.v1.Message.getDefaultInstance() : update_;
      }
    }
    /**
     * <pre>
     * A message associated with the status.
     * </pre>
     *
     * <code>.a2a.v1.Message update = 2 [json_name = "message"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder> 
        internalGetUpdateFieldBuilder() {
      if (updateBuilder_ == null) {
        updateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.a2a.v1.Message, com.google.a2a.v1.Message.Builder, com.google.a2a.v1.MessageOrBuilder>(
                getUpdate(),
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      return updateBuilder_;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          timestamp_ != null &&
          timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <pre>
     * Timestamp when the status was recorded.
     * Example: "2023-10-27T10:00:00Z"
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.TaskStatus)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.TaskStatus)
  private static final com.google.a2a.v1.TaskStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.a2a.v1.TaskStatus();
  }

  public static com.google.a2a.v1.TaskStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskStatus>
      PARSER = new com.google.protobuf.AbstractParser<TaskStatus>() {
    @java.lang.Override
    public TaskStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TaskStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.a2a.v1.TaskStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

